// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: api/proto/combat/combat.proto

package combat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CombatEngineService_InitCombatState_FullMethodName      = "/combat.CombatEngineService/InitCombatState"
	CombatEngineService_CampaignMatchmaking_FullMethodName  = "/combat.CombatEngineService/CampaignMatchmaking"
	CombatEngineService_GetCombatState_FullMethodName       = "/combat.CombatEngineService/GetCombatState"
	CombatEngineService_GetCombatFormulas_FullMethodName    = "/combat.CombatEngineService/GetCombatFormulas"
	CombatEngineService_ExecuteAttack_FullMethodName        = "/combat.CombatEngineService/ExecuteAttack"
	CombatEngineService_ExecuteBlock_FullMethodName         = "/combat.CombatEngineService/ExecuteBlock"
	CombatEngineService_ExecuteDodge_FullMethodName         = "/combat.CombatEngineService/ExecuteDodge"
	CombatEngineService_ExecuteCounter_FullMethodName       = "/combat.CombatEngineService/ExecuteCounter"
	CombatEngineService_ActivateActiveSkill_FullMethodName  = "/combat.CombatEngineService/ActivateActiveSkill"
	CombatEngineService_ApplyTeamPassives_FullMethodName    = "/combat.CombatEngineService/ApplyTeamPassives"
	CombatEngineService_CalculateTurnOutcome_FullMethodName = "/combat.CombatEngineService/CalculateTurnOutcome"
	CombatEngineService_ApplyTickEffects_FullMethodName     = "/combat.CombatEngineService/ApplyTickEffects"
	CombatEngineService_ForceEndCombat_FullMethodName       = "/combat.CombatEngineService/ForceEndCombat"
)

// CombatEngineServiceClient is the client API for CombatEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CombatEngineServiceClient interface {
	// Initialization
	InitCombatState(ctx context.Context, in *InitCombatRequest, opts ...grpc.CallOption) (*InitCombatResponse, error)
	CampaignMatchmaking(ctx context.Context, in *MatchmakingRequest, opts ...grpc.CallOption) (*MatchmakingResponse, error)
	// State retrieval
	GetCombatState(ctx context.Context, in *CombatRequest, opts ...grpc.CallOption) (*CombatStateResponse, error)
	GetCombatFormulas(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FormulasResponse, error)
	// Actions
	ExecuteAttack(ctx context.Context, in *CombatActionRequest, opts ...grpc.CallOption) (*CombatActionResponse, error)
	ExecuteBlock(ctx context.Context, in *CombatActionRequest, opts ...grpc.CallOption) (*CombatActionResponse, error)
	ExecuteDodge(ctx context.Context, in *CombatActionRequest, opts ...grpc.CallOption) (*CombatActionResponse, error)
	ExecuteCounter(ctx context.Context, in *CombatActionRequest, opts ...grpc.CallOption) (*CombatActionResponse, error)
	ActivateActiveSkill(ctx context.Context, in *SkillActionRequest, opts ...grpc.CallOption) (*CombatActionResponse, error)
	// Turn / Mechanics
	ApplyTeamPassives(ctx context.Context, in *CombatRequest, opts ...grpc.CallOption) (*CombatStateResponse, error)
	CalculateTurnOutcome(ctx context.Context, in *CombatRequest, opts ...grpc.CallOption) (*TurnOutcomeResponse, error)
	ApplyTickEffects(ctx context.Context, in *CombatRequest, opts ...grpc.CallOption) (*CombatStateResponse, error)
	// End Condition
	ForceEndCombat(ctx context.Context, in *CombatRequest, opts ...grpc.CallOption) (*EndCombatResponse, error)
}

type combatEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCombatEngineServiceClient(cc grpc.ClientConnInterface) CombatEngineServiceClient {
	return &combatEngineServiceClient{cc}
}

func (c *combatEngineServiceClient) InitCombatState(ctx context.Context, in *InitCombatRequest, opts ...grpc.CallOption) (*InitCombatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitCombatResponse)
	err := c.cc.Invoke(ctx, CombatEngineService_InitCombatState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatEngineServiceClient) CampaignMatchmaking(ctx context.Context, in *MatchmakingRequest, opts ...grpc.CallOption) (*MatchmakingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchmakingResponse)
	err := c.cc.Invoke(ctx, CombatEngineService_CampaignMatchmaking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatEngineServiceClient) GetCombatState(ctx context.Context, in *CombatRequest, opts ...grpc.CallOption) (*CombatStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CombatStateResponse)
	err := c.cc.Invoke(ctx, CombatEngineService_GetCombatState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatEngineServiceClient) GetCombatFormulas(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FormulasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FormulasResponse)
	err := c.cc.Invoke(ctx, CombatEngineService_GetCombatFormulas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatEngineServiceClient) ExecuteAttack(ctx context.Context, in *CombatActionRequest, opts ...grpc.CallOption) (*CombatActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CombatActionResponse)
	err := c.cc.Invoke(ctx, CombatEngineService_ExecuteAttack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatEngineServiceClient) ExecuteBlock(ctx context.Context, in *CombatActionRequest, opts ...grpc.CallOption) (*CombatActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CombatActionResponse)
	err := c.cc.Invoke(ctx, CombatEngineService_ExecuteBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatEngineServiceClient) ExecuteDodge(ctx context.Context, in *CombatActionRequest, opts ...grpc.CallOption) (*CombatActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CombatActionResponse)
	err := c.cc.Invoke(ctx, CombatEngineService_ExecuteDodge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatEngineServiceClient) ExecuteCounter(ctx context.Context, in *CombatActionRequest, opts ...grpc.CallOption) (*CombatActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CombatActionResponse)
	err := c.cc.Invoke(ctx, CombatEngineService_ExecuteCounter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatEngineServiceClient) ActivateActiveSkill(ctx context.Context, in *SkillActionRequest, opts ...grpc.CallOption) (*CombatActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CombatActionResponse)
	err := c.cc.Invoke(ctx, CombatEngineService_ActivateActiveSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatEngineServiceClient) ApplyTeamPassives(ctx context.Context, in *CombatRequest, opts ...grpc.CallOption) (*CombatStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CombatStateResponse)
	err := c.cc.Invoke(ctx, CombatEngineService_ApplyTeamPassives_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatEngineServiceClient) CalculateTurnOutcome(ctx context.Context, in *CombatRequest, opts ...grpc.CallOption) (*TurnOutcomeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TurnOutcomeResponse)
	err := c.cc.Invoke(ctx, CombatEngineService_CalculateTurnOutcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatEngineServiceClient) ApplyTickEffects(ctx context.Context, in *CombatRequest, opts ...grpc.CallOption) (*CombatStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CombatStateResponse)
	err := c.cc.Invoke(ctx, CombatEngineService_ApplyTickEffects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *combatEngineServiceClient) ForceEndCombat(ctx context.Context, in *CombatRequest, opts ...grpc.CallOption) (*EndCombatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndCombatResponse)
	err := c.cc.Invoke(ctx, CombatEngineService_ForceEndCombat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CombatEngineServiceServer is the server API for CombatEngineService service.
// All implementations must embed UnimplementedCombatEngineServiceServer
// for forward compatibility.
type CombatEngineServiceServer interface {
	// Initialization
	InitCombatState(context.Context, *InitCombatRequest) (*InitCombatResponse, error)
	CampaignMatchmaking(context.Context, *MatchmakingRequest) (*MatchmakingResponse, error)
	// State retrieval
	GetCombatState(context.Context, *CombatRequest) (*CombatStateResponse, error)
	GetCombatFormulas(context.Context, *Empty) (*FormulasResponse, error)
	// Actions
	ExecuteAttack(context.Context, *CombatActionRequest) (*CombatActionResponse, error)
	ExecuteBlock(context.Context, *CombatActionRequest) (*CombatActionResponse, error)
	ExecuteDodge(context.Context, *CombatActionRequest) (*CombatActionResponse, error)
	ExecuteCounter(context.Context, *CombatActionRequest) (*CombatActionResponse, error)
	ActivateActiveSkill(context.Context, *SkillActionRequest) (*CombatActionResponse, error)
	// Turn / Mechanics
	ApplyTeamPassives(context.Context, *CombatRequest) (*CombatStateResponse, error)
	CalculateTurnOutcome(context.Context, *CombatRequest) (*TurnOutcomeResponse, error)
	ApplyTickEffects(context.Context, *CombatRequest) (*CombatStateResponse, error)
	// End Condition
	ForceEndCombat(context.Context, *CombatRequest) (*EndCombatResponse, error)
	mustEmbedUnimplementedCombatEngineServiceServer()
}

// UnimplementedCombatEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCombatEngineServiceServer struct{}

func (UnimplementedCombatEngineServiceServer) InitCombatState(context.Context, *InitCombatRequest) (*InitCombatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitCombatState not implemented")
}
func (UnimplementedCombatEngineServiceServer) CampaignMatchmaking(context.Context, *MatchmakingRequest) (*MatchmakingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CampaignMatchmaking not implemented")
}
func (UnimplementedCombatEngineServiceServer) GetCombatState(context.Context, *CombatRequest) (*CombatStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCombatState not implemented")
}
func (UnimplementedCombatEngineServiceServer) GetCombatFormulas(context.Context, *Empty) (*FormulasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCombatFormulas not implemented")
}
func (UnimplementedCombatEngineServiceServer) ExecuteAttack(context.Context, *CombatActionRequest) (*CombatActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteAttack not implemented")
}
func (UnimplementedCombatEngineServiceServer) ExecuteBlock(context.Context, *CombatActionRequest) (*CombatActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteBlock not implemented")
}
func (UnimplementedCombatEngineServiceServer) ExecuteDodge(context.Context, *CombatActionRequest) (*CombatActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteDodge not implemented")
}
func (UnimplementedCombatEngineServiceServer) ExecuteCounter(context.Context, *CombatActionRequest) (*CombatActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCounter not implemented")
}
func (UnimplementedCombatEngineServiceServer) ActivateActiveSkill(context.Context, *SkillActionRequest) (*CombatActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateActiveSkill not implemented")
}
func (UnimplementedCombatEngineServiceServer) ApplyTeamPassives(context.Context, *CombatRequest) (*CombatStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyTeamPassives not implemented")
}
func (UnimplementedCombatEngineServiceServer) CalculateTurnOutcome(context.Context, *CombatRequest) (*TurnOutcomeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateTurnOutcome not implemented")
}
func (UnimplementedCombatEngineServiceServer) ApplyTickEffects(context.Context, *CombatRequest) (*CombatStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyTickEffects not implemented")
}
func (UnimplementedCombatEngineServiceServer) ForceEndCombat(context.Context, *CombatRequest) (*EndCombatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForceEndCombat not implemented")
}
func (UnimplementedCombatEngineServiceServer) mustEmbedUnimplementedCombatEngineServiceServer() {}
func (UnimplementedCombatEngineServiceServer) testEmbeddedByValue()                             {}

// UnsafeCombatEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CombatEngineServiceServer will
// result in compilation errors.
type UnsafeCombatEngineServiceServer interface {
	mustEmbedUnimplementedCombatEngineServiceServer()
}

func RegisterCombatEngineServiceServer(s grpc.ServiceRegistrar, srv CombatEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedCombatEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CombatEngineService_ServiceDesc, srv)
}

func _CombatEngineService_InitCombatState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitCombatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatEngineServiceServer).InitCombatState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatEngineService_InitCombatState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatEngineServiceServer).InitCombatState(ctx, req.(*InitCombatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CombatEngineService_CampaignMatchmaking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchmakingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatEngineServiceServer).CampaignMatchmaking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatEngineService_CampaignMatchmaking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatEngineServiceServer).CampaignMatchmaking(ctx, req.(*MatchmakingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CombatEngineService_GetCombatState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CombatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatEngineServiceServer).GetCombatState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatEngineService_GetCombatState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatEngineServiceServer).GetCombatState(ctx, req.(*CombatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CombatEngineService_GetCombatFormulas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatEngineServiceServer).GetCombatFormulas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatEngineService_GetCombatFormulas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatEngineServiceServer).GetCombatFormulas(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CombatEngineService_ExecuteAttack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CombatActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatEngineServiceServer).ExecuteAttack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatEngineService_ExecuteAttack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatEngineServiceServer).ExecuteAttack(ctx, req.(*CombatActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CombatEngineService_ExecuteBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CombatActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatEngineServiceServer).ExecuteBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatEngineService_ExecuteBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatEngineServiceServer).ExecuteBlock(ctx, req.(*CombatActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CombatEngineService_ExecuteDodge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CombatActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatEngineServiceServer).ExecuteDodge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatEngineService_ExecuteDodge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatEngineServiceServer).ExecuteDodge(ctx, req.(*CombatActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CombatEngineService_ExecuteCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CombatActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatEngineServiceServer).ExecuteCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatEngineService_ExecuteCounter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatEngineServiceServer).ExecuteCounter(ctx, req.(*CombatActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CombatEngineService_ActivateActiveSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatEngineServiceServer).ActivateActiveSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatEngineService_ActivateActiveSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatEngineServiceServer).ActivateActiveSkill(ctx, req.(*SkillActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CombatEngineService_ApplyTeamPassives_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CombatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatEngineServiceServer).ApplyTeamPassives(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatEngineService_ApplyTeamPassives_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatEngineServiceServer).ApplyTeamPassives(ctx, req.(*CombatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CombatEngineService_CalculateTurnOutcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CombatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatEngineServiceServer).CalculateTurnOutcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatEngineService_CalculateTurnOutcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatEngineServiceServer).CalculateTurnOutcome(ctx, req.(*CombatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CombatEngineService_ApplyTickEffects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CombatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatEngineServiceServer).ApplyTickEffects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatEngineService_ApplyTickEffects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatEngineServiceServer).ApplyTickEffects(ctx, req.(*CombatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CombatEngineService_ForceEndCombat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CombatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatEngineServiceServer).ForceEndCombat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatEngineService_ForceEndCombat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatEngineServiceServer).ForceEndCombat(ctx, req.(*CombatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CombatEngineService_ServiceDesc is the grpc.ServiceDesc for CombatEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CombatEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "combat.CombatEngineService",
	HandlerType: (*CombatEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitCombatState",
			Handler:    _CombatEngineService_InitCombatState_Handler,
		},
		{
			MethodName: "CampaignMatchmaking",
			Handler:    _CombatEngineService_CampaignMatchmaking_Handler,
		},
		{
			MethodName: "GetCombatState",
			Handler:    _CombatEngineService_GetCombatState_Handler,
		},
		{
			MethodName: "GetCombatFormulas",
			Handler:    _CombatEngineService_GetCombatFormulas_Handler,
		},
		{
			MethodName: "ExecuteAttack",
			Handler:    _CombatEngineService_ExecuteAttack_Handler,
		},
		{
			MethodName: "ExecuteBlock",
			Handler:    _CombatEngineService_ExecuteBlock_Handler,
		},
		{
			MethodName: "ExecuteDodge",
			Handler:    _CombatEngineService_ExecuteDodge_Handler,
		},
		{
			MethodName: "ExecuteCounter",
			Handler:    _CombatEngineService_ExecuteCounter_Handler,
		},
		{
			MethodName: "ActivateActiveSkill",
			Handler:    _CombatEngineService_ActivateActiveSkill_Handler,
		},
		{
			MethodName: "ApplyTeamPassives",
			Handler:    _CombatEngineService_ApplyTeamPassives_Handler,
		},
		{
			MethodName: "CalculateTurnOutcome",
			Handler:    _CombatEngineService_CalculateTurnOutcome_Handler,
		},
		{
			MethodName: "ApplyTickEffects",
			Handler:    _CombatEngineService_ApplyTickEffects_Handler,
		},
		{
			MethodName: "ForceEndCombat",
			Handler:    _CombatEngineService_ForceEndCombat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/combat/combat.proto",
}
