// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/combat/combat.proto

package combat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{0}
}

type InitCombatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerTeam    []*Character           `protobuf:"bytes,2,rep,name=player_team,json=playerTeam,proto3" json:"player_team,omitempty"`
	EnemyTeam     []*Character           `protobuf:"bytes,3,rep,name=enemy_team,json=enemyTeam,proto3" json:"enemy_team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitCombatRequest) Reset() {
	*x = InitCombatRequest{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitCombatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitCombatRequest) ProtoMessage() {}

func (x *InitCombatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitCombatRequest.ProtoReflect.Descriptor instead.
func (*InitCombatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{1}
}

func (x *InitCombatRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *InitCombatRequest) GetPlayerTeam() []*Character {
	if x != nil {
		return x.PlayerTeam
	}
	return nil
}

func (x *InitCombatRequest) GetEnemyTeam() []*Character {
	if x != nil {
		return x.EnemyTeam
	}
	return nil
}

type InitCombatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CombatId      string                 `protobuf:"bytes,1,opt,name=combat_id,json=combatId,proto3" json:"combat_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitCombatResponse) Reset() {
	*x = InitCombatResponse{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitCombatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitCombatResponse) ProtoMessage() {}

func (x *InitCombatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitCombatResponse.ProtoReflect.Descriptor instead.
func (*InitCombatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{2}
}

func (x *InitCombatResponse) GetCombatId() string {
	if x != nil {
		return x.CombatId
	}
	return ""
}

func (x *InitCombatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MatchmakingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Stage         int32                  `protobuf:"varint,2,opt,name=stage,proto3" json:"stage,omitempty"`
	PlayerTeam    []*Character           `protobuf:"bytes,3,rep,name=player_team,json=playerTeam,proto3" json:"player_team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchmakingRequest) Reset() {
	*x = MatchmakingRequest{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchmakingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchmakingRequest) ProtoMessage() {}

func (x *MatchmakingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchmakingRequest.ProtoReflect.Descriptor instead.
func (*MatchmakingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{3}
}

func (x *MatchmakingRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MatchmakingRequest) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

func (x *MatchmakingRequest) GetPlayerTeam() []*Character {
	if x != nil {
		return x.PlayerTeam
	}
	return nil
}

type MatchmakingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CombatId        string                 `protobuf:"bytes,1,opt,name=combat_id,json=combatId,proto3" json:"combat_id,omitempty"`
	ScaledEnemyTeam []*Character           `protobuf:"bytes,2,rep,name=scaled_enemy_team,json=scaledEnemyTeam,proto3" json:"scaled_enemy_team,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchmakingResponse) Reset() {
	*x = MatchmakingResponse{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchmakingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchmakingResponse) ProtoMessage() {}

func (x *MatchmakingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchmakingResponse.ProtoReflect.Descriptor instead.
func (*MatchmakingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{4}
}

func (x *MatchmakingResponse) GetCombatId() string {
	if x != nil {
		return x.CombatId
	}
	return ""
}

func (x *MatchmakingResponse) GetScaledEnemyTeam() []*Character {
	if x != nil {
		return x.ScaledEnemyTeam
	}
	return nil
}

type CombatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CombatId      string                 `protobuf:"bytes,1,opt,name=combat_id,json=combatId,proto3" json:"combat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatRequest) Reset() {
	*x = CombatRequest{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatRequest) ProtoMessage() {}

func (x *CombatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatRequest.ProtoReflect.Descriptor instead.
func (*CombatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{5}
}

func (x *CombatRequest) GetCombatId() string {
	if x != nil {
		return x.CombatId
	}
	return ""
}

type CombatStateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CombatId        string                 `protobuf:"bytes,1,opt,name=combat_id,json=combatId,proto3" json:"combat_id,omitempty"`
	CurrentTurn     int32                  `protobuf:"varint,2,opt,name=current_turn,json=currentTurn,proto3" json:"current_turn,omitempty"`
	PlayerTeamState []*CharacterState      `protobuf:"bytes,3,rep,name=player_team_state,json=playerTeamState,proto3" json:"player_team_state,omitempty"`
	EnemyTeamState  []*CharacterState      `protobuf:"bytes,4,rep,name=enemy_team_state,json=enemyTeamState,proto3" json:"enemy_team_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CombatStateResponse) Reset() {
	*x = CombatStateResponse{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatStateResponse) ProtoMessage() {}

func (x *CombatStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatStateResponse.ProtoReflect.Descriptor instead.
func (*CombatStateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{6}
}

func (x *CombatStateResponse) GetCombatId() string {
	if x != nil {
		return x.CombatId
	}
	return ""
}

func (x *CombatStateResponse) GetCurrentTurn() int32 {
	if x != nil {
		return x.CurrentTurn
	}
	return 0
}

func (x *CombatStateResponse) GetPlayerTeamState() []*CharacterState {
	if x != nil {
		return x.PlayerTeamState
	}
	return nil
}

func (x *CombatStateResponse) GetEnemyTeamState() []*CharacterState {
	if x != nil {
		return x.EnemyTeamState
	}
	return nil
}

type FormulasResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BlockFormula       string                 `protobuf:"bytes,1,opt,name=block_formula,json=blockFormula,proto3" json:"block_formula,omitempty"`
	DodgeFormula       string                 `protobuf:"bytes,2,opt,name=dodge_formula,json=dodgeFormula,proto3" json:"dodge_formula,omitempty"`
	CounterFormula     string                 `protobuf:"bytes,3,opt,name=counter_formula,json=counterFormula,proto3" json:"counter_formula,omitempty"`
	ActiveSkillFormula string                 `protobuf:"bytes,4,opt,name=active_skill_formula,json=activeSkillFormula,proto3" json:"active_skill_formula,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FormulasResponse) Reset() {
	*x = FormulasResponse{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormulasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormulasResponse) ProtoMessage() {}

func (x *FormulasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormulasResponse.ProtoReflect.Descriptor instead.
func (*FormulasResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{7}
}

func (x *FormulasResponse) GetBlockFormula() string {
	if x != nil {
		return x.BlockFormula
	}
	return ""
}

func (x *FormulasResponse) GetDodgeFormula() string {
	if x != nil {
		return x.DodgeFormula
	}
	return ""
}

func (x *FormulasResponse) GetCounterFormula() string {
	if x != nil {
		return x.CounterFormula
	}
	return ""
}

func (x *FormulasResponse) GetActiveSkillFormula() string {
	if x != nil {
		return x.ActiveSkillFormula
	}
	return ""
}

type CombatActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CombatId      string                 `protobuf:"bytes,1,opt,name=combat_id,json=combatId,proto3" json:"combat_id,omitempty"`
	AttackerId    string                 `protobuf:"bytes,2,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatActionRequest) Reset() {
	*x = CombatActionRequest{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatActionRequest) ProtoMessage() {}

func (x *CombatActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatActionRequest.ProtoReflect.Descriptor instead.
func (*CombatActionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{8}
}

func (x *CombatActionRequest) GetCombatId() string {
	if x != nil {
		return x.CombatId
	}
	return ""
}

func (x *CombatActionRequest) GetAttackerId() string {
	if x != nil {
		return x.AttackerId
	}
	return ""
}

func (x *CombatActionRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type SkillActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CombatId      string                 `protobuf:"bytes,1,opt,name=combat_id,json=combatId,proto3" json:"combat_id,omitempty"`
	AttackerId    string                 `protobuf:"bytes,2,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	SkillName     string                 `protobuf:"bytes,4,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillActionRequest) Reset() {
	*x = SkillActionRequest{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillActionRequest) ProtoMessage() {}

func (x *SkillActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillActionRequest.ProtoReflect.Descriptor instead.
func (*SkillActionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{9}
}

func (x *SkillActionRequest) GetCombatId() string {
	if x != nil {
		return x.CombatId
	}
	return ""
}

func (x *SkillActionRequest) GetAttackerId() string {
	if x != nil {
		return x.AttackerId
	}
	return ""
}

func (x *SkillActionRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *SkillActionRequest) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

type CombatActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DamageDealt   int32                  `protobuf:"varint,2,opt,name=damage_dealt,json=damageDealt,proto3" json:"damage_dealt,omitempty"`
	ActionLog     string                 `protobuf:"bytes,3,opt,name=action_log,json=actionLog,proto3" json:"action_log,omitempty"`
	IsCritical    bool                   `protobuf:"varint,4,opt,name=is_critical,json=isCritical,proto3" json:"is_critical,omitempty"`
	IsDodged      bool                   `protobuf:"varint,5,opt,name=is_dodged,json=isDodged,proto3" json:"is_dodged,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,6,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	IsCountered   bool                   `protobuf:"varint,7,opt,name=is_countered,json=isCountered,proto3" json:"is_countered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatActionResponse) Reset() {
	*x = CombatActionResponse{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatActionResponse) ProtoMessage() {}

func (x *CombatActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatActionResponse.ProtoReflect.Descriptor instead.
func (*CombatActionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{10}
}

func (x *CombatActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CombatActionResponse) GetDamageDealt() int32 {
	if x != nil {
		return x.DamageDealt
	}
	return 0
}

func (x *CombatActionResponse) GetActionLog() string {
	if x != nil {
		return x.ActionLog
	}
	return ""
}

func (x *CombatActionResponse) GetIsCritical() bool {
	if x != nil {
		return x.IsCritical
	}
	return false
}

func (x *CombatActionResponse) GetIsDodged() bool {
	if x != nil {
		return x.IsDodged
	}
	return false
}

func (x *CombatActionResponse) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *CombatActionResponse) GetIsCountered() bool {
	if x != nil {
		return x.IsCountered
	}
	return false
}

type TurnOutcomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CombatId      string                 `protobuf:"bytes,1,opt,name=combat_id,json=combatId,proto3" json:"combat_id,omitempty"`
	TurnLog       string                 `protobuf:"bytes,2,opt,name=turn_log,json=turnLog,proto3" json:"turn_log,omitempty"`
	CombatEnded   bool                   `protobuf:"varint,3,opt,name=combat_ended,json=combatEnded,proto3" json:"combat_ended,omitempty"`
	Winner        string                 `protobuf:"bytes,4,opt,name=winner,proto3" json:"winner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnOutcomeResponse) Reset() {
	*x = TurnOutcomeResponse{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnOutcomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnOutcomeResponse) ProtoMessage() {}

func (x *TurnOutcomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnOutcomeResponse.ProtoReflect.Descriptor instead.
func (*TurnOutcomeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{11}
}

func (x *TurnOutcomeResponse) GetCombatId() string {
	if x != nil {
		return x.CombatId
	}
	return ""
}

func (x *TurnOutcomeResponse) GetTurnLog() string {
	if x != nil {
		return x.TurnLog
	}
	return ""
}

func (x *TurnOutcomeResponse) GetCombatEnded() bool {
	if x != nil {
		return x.CombatEnded
	}
	return false
}

func (x *TurnOutcomeResponse) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

type EndCombatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Winner        string                 `protobuf:"bytes,2,opt,name=winner,proto3" json:"winner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCombatResponse) Reset() {
	*x = EndCombatResponse{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCombatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCombatResponse) ProtoMessage() {}

func (x *EndCombatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCombatResponse.ProtoReflect.Descriptor instead.
func (*EndCombatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{12}
}

func (x *EndCombatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EndCombatResponse) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

type Character struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Name       string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Level      int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	MergeStars int32                  `protobuf:"varint,5,opt,name=merge_stars,json=mergeStars,proto3" json:"merge_stars,omitempty"`
	// Base Stats
	Hp         int32   `protobuf:"varint,6,opt,name=hp,proto3" json:"hp,omitempty"`
	Str        int32   `protobuf:"varint,7,opt,name=str,proto3" json:"str,omitempty"`
	Mana       int32   `protobuf:"varint,8,opt,name=mana,proto3" json:"mana,omitempty"`
	Agility    int32   `protobuf:"varint,9,opt,name=agility,proto3" json:"agility,omitempty"`
	Reaction   int32   `protobuf:"varint,10,opt,name=reaction,proto3" json:"reaction,omitempty"`
	Durability int32   `protobuf:"varint,11,opt,name=durability,proto3" json:"durability,omitempty"`
	Power      float32 `protobuf:"fixed32,12,opt,name=power,proto3" json:"power,omitempty"`
	Speed      float32 `protobuf:"fixed32,13,opt,name=speed,proto3" json:"speed,omitempty"`
	Technique  float32 `protobuf:"fixed32,14,opt,name=technique,proto3" json:"technique,omitempty"`
	// JSON-encoded skill configs
	PassiveSkill  string `protobuf:"bytes,15,opt,name=passive_skill,json=passiveSkill,proto3" json:"passive_skill,omitempty"`
	ActiveSkill   string `protobuf:"bytes,16,opt,name=active_skill,json=activeSkill,proto3" json:"active_skill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{13}
}

func (x *Character) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Character) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Character) GetMergeStars() int32 {
	if x != nil {
		return x.MergeStars
	}
	return 0
}

func (x *Character) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Character) GetStr() int32 {
	if x != nil {
		return x.Str
	}
	return 0
}

func (x *Character) GetMana() int32 {
	if x != nil {
		return x.Mana
	}
	return 0
}

func (x *Character) GetAgility() int32 {
	if x != nil {
		return x.Agility
	}
	return 0
}

func (x *Character) GetReaction() int32 {
	if x != nil {
		return x.Reaction
	}
	return 0
}

func (x *Character) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *Character) GetPower() float32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *Character) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Character) GetTechnique() float32 {
	if x != nil {
		return x.Technique
	}
	return 0
}

func (x *Character) GetPassiveSkill() string {
	if x != nil {
		return x.PassiveSkill
	}
	return ""
}

func (x *Character) GetActiveSkill() string {
	if x != nil {
		return x.ActiveSkill
	}
	return ""
}

type CharacterState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentHp     int32                  `protobuf:"varint,2,opt,name=current_hp,json=currentHp,proto3" json:"current_hp,omitempty"`
	CurrentMana   int32                  `protobuf:"varint,3,opt,name=current_mana,json=currentMana,proto3" json:"current_mana,omitempty"`
	Effects       []*StatusEffect        `protobuf:"bytes,4,rep,name=effects,proto3" json:"effects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterState) Reset() {
	*x = CharacterState{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterState) ProtoMessage() {}

func (x *CharacterState) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterState.ProtoReflect.Descriptor instead.
func (*CharacterState) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{14}
}

func (x *CharacterState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CharacterState) GetCurrentHp() int32 {
	if x != nil {
		return x.CurrentHp
	}
	return 0
}

func (x *CharacterState) GetCurrentMana() int32 {
	if x != nil {
		return x.CurrentMana
	}
	return 0
}

func (x *CharacterState) GetEffects() []*StatusEffect {
	if x != nil {
		return x.Effects
	}
	return nil
}

type StatusEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DurationTurns int32                  `protobuf:"varint,2,opt,name=duration_turns,json=durationTurns,proto3" json:"duration_turns,omitempty"`
	EffectType    string                 `protobuf:"bytes,3,opt,name=effect_type,json=effectType,proto3" json:"effect_type,omitempty"` // e.g. "buff_tech", "debuff_durability"
	Value         float32                `protobuf:"fixed32,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEffect) Reset() {
	*x = StatusEffect{}
	mi := &file_api_proto_combat_combat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEffect) ProtoMessage() {}

func (x *StatusEffect) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_combat_combat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEffect.ProtoReflect.Descriptor instead.
func (*StatusEffect) Descriptor() ([]byte, []int) {
	return file_api_proto_combat_combat_proto_rawDescGZIP(), []int{15}
}

func (x *StatusEffect) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusEffect) GetDurationTurns() int32 {
	if x != nil {
		return x.DurationTurns
	}
	return 0
}

func (x *StatusEffect) GetEffectType() string {
	if x != nil {
		return x.EffectType
	}
	return ""
}

func (x *StatusEffect) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_api_proto_combat_combat_proto protoreflect.FileDescriptor

const file_api_proto_combat_combat_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/combat/combat.proto\x12\x06combat\"\a\n" +
	"\x05Empty\"\x96\x01\n" +
	"\x11InitCombatRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x122\n" +
	"\vplayer_team\x18\x02 \x03(\v2\x11.combat.CharacterR\n" +
	"playerTeam\x120\n" +
	"\n" +
	"enemy_team\x18\x03 \x03(\v2\x11.combat.CharacterR\tenemyTeam\"K\n" +
	"\x12InitCombatResponse\x12\x1b\n" +
	"\tcombat_id\x18\x01 \x01(\tR\bcombatId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"{\n" +
	"\x12MatchmakingRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\x05R\x05stage\x122\n" +
	"\vplayer_team\x18\x03 \x03(\v2\x11.combat.CharacterR\n" +
	"playerTeam\"q\n" +
	"\x13MatchmakingResponse\x12\x1b\n" +
	"\tcombat_id\x18\x01 \x01(\tR\bcombatId\x12=\n" +
	"\x11scaled_enemy_team\x18\x02 \x03(\v2\x11.combat.CharacterR\x0fscaledEnemyTeam\",\n" +
	"\rCombatRequest\x12\x1b\n" +
	"\tcombat_id\x18\x01 \x01(\tR\bcombatId\"\xdb\x01\n" +
	"\x13CombatStateResponse\x12\x1b\n" +
	"\tcombat_id\x18\x01 \x01(\tR\bcombatId\x12!\n" +
	"\fcurrent_turn\x18\x02 \x01(\x05R\vcurrentTurn\x12B\n" +
	"\x11player_team_state\x18\x03 \x03(\v2\x16.combat.CharacterStateR\x0fplayerTeamState\x12@\n" +
	"\x10enemy_team_state\x18\x04 \x03(\v2\x16.combat.CharacterStateR\x0eenemyTeamState\"\xb7\x01\n" +
	"\x10FormulasResponse\x12#\n" +
	"\rblock_formula\x18\x01 \x01(\tR\fblockFormula\x12#\n" +
	"\rdodge_formula\x18\x02 \x01(\tR\fdodgeFormula\x12'\n" +
	"\x0fcounter_formula\x18\x03 \x01(\tR\x0ecounterFormula\x120\n" +
	"\x14active_skill_formula\x18\x04 \x01(\tR\x12activeSkillFormula\"p\n" +
	"\x13CombatActionRequest\x12\x1b\n" +
	"\tcombat_id\x18\x01 \x01(\tR\bcombatId\x12\x1f\n" +
	"\vattacker_id\x18\x02 \x01(\tR\n" +
	"attackerId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\"\x8e\x01\n" +
	"\x12SkillActionRequest\x12\x1b\n" +
	"\tcombat_id\x18\x01 \x01(\tR\bcombatId\x12\x1f\n" +
	"\vattacker_id\x18\x02 \x01(\tR\n" +
	"attackerId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x04 \x01(\tR\tskillName\"\xf2\x01\n" +
	"\x14CombatActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fdamage_dealt\x18\x02 \x01(\x05R\vdamageDealt\x12\x1d\n" +
	"\n" +
	"action_log\x18\x03 \x01(\tR\tactionLog\x12\x1f\n" +
	"\vis_critical\x18\x04 \x01(\bR\n" +
	"isCritical\x12\x1b\n" +
	"\tis_dodged\x18\x05 \x01(\bR\bisDodged\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x06 \x01(\bR\tisBlocked\x12!\n" +
	"\fis_countered\x18\a \x01(\bR\visCountered\"\x88\x01\n" +
	"\x13TurnOutcomeResponse\x12\x1b\n" +
	"\tcombat_id\x18\x01 \x01(\tR\bcombatId\x12\x19\n" +
	"\bturn_log\x18\x02 \x01(\tR\aturnLog\x12!\n" +
	"\fcombat_ended\x18\x03 \x01(\bR\vcombatEnded\x12\x16\n" +
	"\x06winner\x18\x04 \x01(\tR\x06winner\"E\n" +
	"\x11EndCombatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06winner\x18\x02 \x01(\tR\x06winner\"\xa5\x03\n" +
	"\tCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1f\n" +
	"\vmerge_stars\x18\x05 \x01(\x05R\n" +
	"mergeStars\x12\x0e\n" +
	"\x02hp\x18\x06 \x01(\x05R\x02hp\x12\x10\n" +
	"\x03str\x18\a \x01(\x05R\x03str\x12\x12\n" +
	"\x04mana\x18\b \x01(\x05R\x04mana\x12\x18\n" +
	"\aagility\x18\t \x01(\x05R\aagility\x12\x1a\n" +
	"\breaction\x18\n" +
	" \x01(\x05R\breaction\x12\x1e\n" +
	"\n" +
	"durability\x18\v \x01(\x05R\n" +
	"durability\x12\x14\n" +
	"\x05power\x18\f \x01(\x02R\x05power\x12\x14\n" +
	"\x05speed\x18\r \x01(\x02R\x05speed\x12\x1c\n" +
	"\ttechnique\x18\x0e \x01(\x02R\ttechnique\x12#\n" +
	"\rpassive_skill\x18\x0f \x01(\tR\fpassiveSkill\x12!\n" +
	"\factive_skill\x18\x10 \x01(\tR\vactiveSkill\"\x92\x01\n" +
	"\x0eCharacterState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"current_hp\x18\x02 \x01(\x05R\tcurrentHp\x12!\n" +
	"\fcurrent_mana\x18\x03 \x01(\x05R\vcurrentMana\x12.\n" +
	"\aeffects\x18\x04 \x03(\v2\x14.combat.StatusEffectR\aeffects\"\x80\x01\n" +
	"\fStatusEffect\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eduration_turns\x18\x02 \x01(\x05R\rdurationTurns\x12\x1f\n" +
	"\veffect_type\x18\x03 \x01(\tR\n" +
	"effectType\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x02R\x05value2\xd4\a\n" +
	"\x13CombatEngineService\x12H\n" +
	"\x0fInitCombatState\x12\x19.combat.InitCombatRequest\x1a\x1a.combat.InitCombatResponse\x12N\n" +
	"\x13CampaignMatchmaking\x12\x1a.combat.MatchmakingRequest\x1a\x1b.combat.MatchmakingResponse\x12D\n" +
	"\x0eGetCombatState\x12\x15.combat.CombatRequest\x1a\x1b.combat.CombatStateResponse\x12<\n" +
	"\x11GetCombatFormulas\x12\r.combat.Empty\x1a\x18.combat.FormulasResponse\x12J\n" +
	"\rExecuteAttack\x12\x1b.combat.CombatActionRequest\x1a\x1c.combat.CombatActionResponse\x12I\n" +
	"\fExecuteBlock\x12\x1b.combat.CombatActionRequest\x1a\x1c.combat.CombatActionResponse\x12I\n" +
	"\fExecuteDodge\x12\x1b.combat.CombatActionRequest\x1a\x1c.combat.CombatActionResponse\x12K\n" +
	"\x0eExecuteCounter\x12\x1b.combat.CombatActionRequest\x1a\x1c.combat.CombatActionResponse\x12O\n" +
	"\x13ActivateActiveSkill\x12\x1a.combat.SkillActionRequest\x1a\x1c.combat.CombatActionResponse\x12G\n" +
	"\x11ApplyTeamPassives\x12\x15.combat.CombatRequest\x1a\x1b.combat.CombatStateResponse\x12J\n" +
	"\x14CalculateTurnOutcome\x12\x15.combat.CombatRequest\x1a\x1b.combat.TurnOutcomeResponse\x12F\n" +
	"\x10ApplyTickEffects\x12\x15.combat.CombatRequest\x1a\x1b.combat.CombatStateResponse\x12B\n" +
	"\x0eForceEndCombat\x12\x15.combat.CombatRequest\x1a\x19.combat.EndCombatResponseB/Z-github.com/kozie/lookism-rpg/api/proto/combatb\x06proto3"

var (
	file_api_proto_combat_combat_proto_rawDescOnce sync.Once
	file_api_proto_combat_combat_proto_rawDescData []byte
)

func file_api_proto_combat_combat_proto_rawDescGZIP() []byte {
	file_api_proto_combat_combat_proto_rawDescOnce.Do(func() {
		file_api_proto_combat_combat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_combat_combat_proto_rawDesc), len(file_api_proto_combat_combat_proto_rawDesc)))
	})
	return file_api_proto_combat_combat_proto_rawDescData
}

var file_api_proto_combat_combat_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_combat_combat_proto_goTypes = []any{
	(*Empty)(nil),                // 0: combat.Empty
	(*InitCombatRequest)(nil),    // 1: combat.InitCombatRequest
	(*InitCombatResponse)(nil),   // 2: combat.InitCombatResponse
	(*MatchmakingRequest)(nil),   // 3: combat.MatchmakingRequest
	(*MatchmakingResponse)(nil),  // 4: combat.MatchmakingResponse
	(*CombatRequest)(nil),        // 5: combat.CombatRequest
	(*CombatStateResponse)(nil),  // 6: combat.CombatStateResponse
	(*FormulasResponse)(nil),     // 7: combat.FormulasResponse
	(*CombatActionRequest)(nil),  // 8: combat.CombatActionRequest
	(*SkillActionRequest)(nil),   // 9: combat.SkillActionRequest
	(*CombatActionResponse)(nil), // 10: combat.CombatActionResponse
	(*TurnOutcomeResponse)(nil),  // 11: combat.TurnOutcomeResponse
	(*EndCombatResponse)(nil),    // 12: combat.EndCombatResponse
	(*Character)(nil),            // 13: combat.Character
	(*CharacterState)(nil),       // 14: combat.CharacterState
	(*StatusEffect)(nil),         // 15: combat.StatusEffect
}
var file_api_proto_combat_combat_proto_depIdxs = []int32{
	13, // 0: combat.InitCombatRequest.player_team:type_name -> combat.Character
	13, // 1: combat.InitCombatRequest.enemy_team:type_name -> combat.Character
	13, // 2: combat.MatchmakingRequest.player_team:type_name -> combat.Character
	13, // 3: combat.MatchmakingResponse.scaled_enemy_team:type_name -> combat.Character
	14, // 4: combat.CombatStateResponse.player_team_state:type_name -> combat.CharacterState
	14, // 5: combat.CombatStateResponse.enemy_team_state:type_name -> combat.CharacterState
	15, // 6: combat.CharacterState.effects:type_name -> combat.StatusEffect
	1,  // 7: combat.CombatEngineService.InitCombatState:input_type -> combat.InitCombatRequest
	3,  // 8: combat.CombatEngineService.CampaignMatchmaking:input_type -> combat.MatchmakingRequest
	5,  // 9: combat.CombatEngineService.GetCombatState:input_type -> combat.CombatRequest
	0,  // 10: combat.CombatEngineService.GetCombatFormulas:input_type -> combat.Empty
	8,  // 11: combat.CombatEngineService.ExecuteAttack:input_type -> combat.CombatActionRequest
	8,  // 12: combat.CombatEngineService.ExecuteBlock:input_type -> combat.CombatActionRequest
	8,  // 13: combat.CombatEngineService.ExecuteDodge:input_type -> combat.CombatActionRequest
	8,  // 14: combat.CombatEngineService.ExecuteCounter:input_type -> combat.CombatActionRequest
	9,  // 15: combat.CombatEngineService.ActivateActiveSkill:input_type -> combat.SkillActionRequest
	5,  // 16: combat.CombatEngineService.ApplyTeamPassives:input_type -> combat.CombatRequest
	5,  // 17: combat.CombatEngineService.CalculateTurnOutcome:input_type -> combat.CombatRequest
	5,  // 18: combat.CombatEngineService.ApplyTickEffects:input_type -> combat.CombatRequest
	5,  // 19: combat.CombatEngineService.ForceEndCombat:input_type -> combat.CombatRequest
	2,  // 20: combat.CombatEngineService.InitCombatState:output_type -> combat.InitCombatResponse
	4,  // 21: combat.CombatEngineService.CampaignMatchmaking:output_type -> combat.MatchmakingResponse
	6,  // 22: combat.CombatEngineService.GetCombatState:output_type -> combat.CombatStateResponse
	7,  // 23: combat.CombatEngineService.GetCombatFormulas:output_type -> combat.FormulasResponse
	10, // 24: combat.CombatEngineService.ExecuteAttack:output_type -> combat.CombatActionResponse
	10, // 25: combat.CombatEngineService.ExecuteBlock:output_type -> combat.CombatActionResponse
	10, // 26: combat.CombatEngineService.ExecuteDodge:output_type -> combat.CombatActionResponse
	10, // 27: combat.CombatEngineService.ExecuteCounter:output_type -> combat.CombatActionResponse
	10, // 28: combat.CombatEngineService.ActivateActiveSkill:output_type -> combat.CombatActionResponse
	6,  // 29: combat.CombatEngineService.ApplyTeamPassives:output_type -> combat.CombatStateResponse
	11, // 30: combat.CombatEngineService.CalculateTurnOutcome:output_type -> combat.TurnOutcomeResponse
	6,  // 31: combat.CombatEngineService.ApplyTickEffects:output_type -> combat.CombatStateResponse
	12, // 32: combat.CombatEngineService.ForceEndCombat:output_type -> combat.EndCombatResponse
	20, // [20:33] is the sub-list for method output_type
	7,  // [7:20] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_combat_combat_proto_init() }
func file_api_proto_combat_combat_proto_init() {
	if File_api_proto_combat_combat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_combat_combat_proto_rawDesc), len(file_api_proto_combat_combat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_combat_combat_proto_goTypes,
		DependencyIndexes: file_api_proto_combat_combat_proto_depIdxs,
		MessageInfos:      file_api_proto_combat_combat_proto_msgTypes,
	}.Build()
	File_api_proto_combat_combat_proto = out.File
	file_api_proto_combat_combat_proto_goTypes = nil
	file_api_proto_combat_combat_proto_depIdxs = nil
}
