// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: api/proto/gacha/gacha.proto

package gacha

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GachaEconomyService_GetBanners_FullMethodName       = "/gacha.GachaEconomyService/GetBanners"
	GachaEconomyService_RollGachaSingle_FullMethodName  = "/gacha.GachaEconomyService/RollGachaSingle"
	GachaEconomyService_RollGachaMulti_FullMethodName   = "/gacha.GachaEconomyService/RollGachaMulti"
	GachaEconomyService_GetEnergyState_FullMethodName   = "/gacha.GachaEconomyService/GetEnergyState"
	GachaEconomyService_ConsumeEnergy_FullMethodName    = "/gacha.GachaEconomyService/ConsumeEnergy"
	GachaEconomyService_AddCurrency_FullMethodName      = "/gacha.GachaEconomyService/AddCurrency"
	GachaEconomyService_SpendCurrency_FullMethodName    = "/gacha.GachaEconomyService/SpendCurrency"
	GachaEconomyService_GetDailyRewards_FullMethodName  = "/gacha.GachaEconomyService/GetDailyRewards"
	GachaEconomyService_ClaimDailyReward_FullMethodName = "/gacha.GachaEconomyService/ClaimDailyReward"
	GachaEconomyService_GetQuests_FullMethodName        = "/gacha.GachaEconomyService/GetQuests"
	GachaEconomyService_ClaimQuestReward_FullMethodName = "/gacha.GachaEconomyService/ClaimQuestReward"
	GachaEconomyService_GetShopItems_FullMethodName     = "/gacha.GachaEconomyService/GetShopItems"
	GachaEconomyService_ShopPurchase_FullMethodName     = "/gacha.GachaEconomyService/ShopPurchase"
	GachaEconomyService_GetFreePackTimer_FullMethodName = "/gacha.GachaEconomyService/GetFreePackTimer"
)

// GachaEconomyServiceClient is the client API for GachaEconomyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GachaEconomyServiceClient interface {
	// Gacha
	GetBanners(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BannerList, error)
	RollGachaSingle(ctx context.Context, in *RollRequest, opts ...grpc.CallOption) (*RollResponse, error)
	RollGachaMulti(ctx context.Context, in *RollRequest, opts ...grpc.CallOption) (*RollResponse, error)
	// Economy & Energy
	GetEnergyState(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*EnergyState, error)
	ConsumeEnergy(ctx context.Context, in *ConsumeEnergyRequest, opts ...grpc.CallOption) (*ConsumeEnergyResponse, error)
	AddCurrency(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (*CurrencyResponse, error)
	SpendCurrency(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (*CurrencyResponse, error)
	// Dailies & Quests
	GetDailyRewards(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*DailyRewardsList, error)
	ClaimDailyReward(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error)
	GetQuests(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*QuestList, error)
	ClaimQuestReward(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error)
	// Shop
	GetShopItems(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ShopItemList, error)
	ShopPurchase(ctx context.Context, in *PurchaseRequest, opts ...grpc.CallOption) (*PurchaseResponse, error)
	// Pack Timers
	GetFreePackTimer(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*TimerResponse, error)
}

type gachaEconomyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGachaEconomyServiceClient(cc grpc.ClientConnInterface) GachaEconomyServiceClient {
	return &gachaEconomyServiceClient{cc}
}

func (c *gachaEconomyServiceClient) GetBanners(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BannerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BannerList)
	err := c.cc.Invoke(ctx, GachaEconomyService_GetBanners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaEconomyServiceClient) RollGachaSingle(ctx context.Context, in *RollRequest, opts ...grpc.CallOption) (*RollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollResponse)
	err := c.cc.Invoke(ctx, GachaEconomyService_RollGachaSingle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaEconomyServiceClient) RollGachaMulti(ctx context.Context, in *RollRequest, opts ...grpc.CallOption) (*RollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollResponse)
	err := c.cc.Invoke(ctx, GachaEconomyService_RollGachaMulti_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaEconomyServiceClient) GetEnergyState(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*EnergyState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnergyState)
	err := c.cc.Invoke(ctx, GachaEconomyService_GetEnergyState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaEconomyServiceClient) ConsumeEnergy(ctx context.Context, in *ConsumeEnergyRequest, opts ...grpc.CallOption) (*ConsumeEnergyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumeEnergyResponse)
	err := c.cc.Invoke(ctx, GachaEconomyService_ConsumeEnergy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaEconomyServiceClient) AddCurrency(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (*CurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurrencyResponse)
	err := c.cc.Invoke(ctx, GachaEconomyService_AddCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaEconomyServiceClient) SpendCurrency(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (*CurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurrencyResponse)
	err := c.cc.Invoke(ctx, GachaEconomyService_SpendCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaEconomyServiceClient) GetDailyRewards(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*DailyRewardsList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailyRewardsList)
	err := c.cc.Invoke(ctx, GachaEconomyService_GetDailyRewards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaEconomyServiceClient) ClaimDailyReward(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimResponse)
	err := c.cc.Invoke(ctx, GachaEconomyService_ClaimDailyReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaEconomyServiceClient) GetQuests(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*QuestList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestList)
	err := c.cc.Invoke(ctx, GachaEconomyService_GetQuests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaEconomyServiceClient) ClaimQuestReward(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimResponse)
	err := c.cc.Invoke(ctx, GachaEconomyService_ClaimQuestReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaEconomyServiceClient) GetShopItems(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ShopItemList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopItemList)
	err := c.cc.Invoke(ctx, GachaEconomyService_GetShopItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaEconomyServiceClient) ShopPurchase(ctx context.Context, in *PurchaseRequest, opts ...grpc.CallOption) (*PurchaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseResponse)
	err := c.cc.Invoke(ctx, GachaEconomyService_ShopPurchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaEconomyServiceClient) GetFreePackTimer(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*TimerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerResponse)
	err := c.cc.Invoke(ctx, GachaEconomyService_GetFreePackTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GachaEconomyServiceServer is the server API for GachaEconomyService service.
// All implementations must embed UnimplementedGachaEconomyServiceServer
// for forward compatibility.
type GachaEconomyServiceServer interface {
	// Gacha
	GetBanners(context.Context, *Empty) (*BannerList, error)
	RollGachaSingle(context.Context, *RollRequest) (*RollResponse, error)
	RollGachaMulti(context.Context, *RollRequest) (*RollResponse, error)
	// Economy & Energy
	GetEnergyState(context.Context, *UserRequest) (*EnergyState, error)
	ConsumeEnergy(context.Context, *ConsumeEnergyRequest) (*ConsumeEnergyResponse, error)
	AddCurrency(context.Context, *CurrencyRequest) (*CurrencyResponse, error)
	SpendCurrency(context.Context, *CurrencyRequest) (*CurrencyResponse, error)
	// Dailies & Quests
	GetDailyRewards(context.Context, *UserRequest) (*DailyRewardsList, error)
	ClaimDailyReward(context.Context, *ClaimRequest) (*ClaimResponse, error)
	GetQuests(context.Context, *UserRequest) (*QuestList, error)
	ClaimQuestReward(context.Context, *ClaimRequest) (*ClaimResponse, error)
	// Shop
	GetShopItems(context.Context, *Empty) (*ShopItemList, error)
	ShopPurchase(context.Context, *PurchaseRequest) (*PurchaseResponse, error)
	// Pack Timers
	GetFreePackTimer(context.Context, *UserRequest) (*TimerResponse, error)
	mustEmbedUnimplementedGachaEconomyServiceServer()
}

// UnimplementedGachaEconomyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGachaEconomyServiceServer struct{}

func (UnimplementedGachaEconomyServiceServer) GetBanners(context.Context, *Empty) (*BannerList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBanners not implemented")
}
func (UnimplementedGachaEconomyServiceServer) RollGachaSingle(context.Context, *RollRequest) (*RollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollGachaSingle not implemented")
}
func (UnimplementedGachaEconomyServiceServer) RollGachaMulti(context.Context, *RollRequest) (*RollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollGachaMulti not implemented")
}
func (UnimplementedGachaEconomyServiceServer) GetEnergyState(context.Context, *UserRequest) (*EnergyState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnergyState not implemented")
}
func (UnimplementedGachaEconomyServiceServer) ConsumeEnergy(context.Context, *ConsumeEnergyRequest) (*ConsumeEnergyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsumeEnergy not implemented")
}
func (UnimplementedGachaEconomyServiceServer) AddCurrency(context.Context, *CurrencyRequest) (*CurrencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCurrency not implemented")
}
func (UnimplementedGachaEconomyServiceServer) SpendCurrency(context.Context, *CurrencyRequest) (*CurrencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SpendCurrency not implemented")
}
func (UnimplementedGachaEconomyServiceServer) GetDailyRewards(context.Context, *UserRequest) (*DailyRewardsList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailyRewards not implemented")
}
func (UnimplementedGachaEconomyServiceServer) ClaimDailyReward(context.Context, *ClaimRequest) (*ClaimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimDailyReward not implemented")
}
func (UnimplementedGachaEconomyServiceServer) GetQuests(context.Context, *UserRequest) (*QuestList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuests not implemented")
}
func (UnimplementedGachaEconomyServiceServer) ClaimQuestReward(context.Context, *ClaimRequest) (*ClaimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimQuestReward not implemented")
}
func (UnimplementedGachaEconomyServiceServer) GetShopItems(context.Context, *Empty) (*ShopItemList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShopItems not implemented")
}
func (UnimplementedGachaEconomyServiceServer) ShopPurchase(context.Context, *PurchaseRequest) (*PurchaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShopPurchase not implemented")
}
func (UnimplementedGachaEconomyServiceServer) GetFreePackTimer(context.Context, *UserRequest) (*TimerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFreePackTimer not implemented")
}
func (UnimplementedGachaEconomyServiceServer) mustEmbedUnimplementedGachaEconomyServiceServer() {}
func (UnimplementedGachaEconomyServiceServer) testEmbeddedByValue()                             {}

// UnsafeGachaEconomyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GachaEconomyServiceServer will
// result in compilation errors.
type UnsafeGachaEconomyServiceServer interface {
	mustEmbedUnimplementedGachaEconomyServiceServer()
}

func RegisterGachaEconomyServiceServer(s grpc.ServiceRegistrar, srv GachaEconomyServiceServer) {
	// If the following call panics, it indicates UnimplementedGachaEconomyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GachaEconomyService_ServiceDesc, srv)
}

func _GachaEconomyService_GetBanners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaEconomyServiceServer).GetBanners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaEconomyService_GetBanners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaEconomyServiceServer).GetBanners(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaEconomyService_RollGachaSingle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaEconomyServiceServer).RollGachaSingle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaEconomyService_RollGachaSingle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaEconomyServiceServer).RollGachaSingle(ctx, req.(*RollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaEconomyService_RollGachaMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaEconomyServiceServer).RollGachaMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaEconomyService_RollGachaMulti_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaEconomyServiceServer).RollGachaMulti(ctx, req.(*RollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaEconomyService_GetEnergyState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaEconomyServiceServer).GetEnergyState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaEconomyService_GetEnergyState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaEconomyServiceServer).GetEnergyState(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaEconomyService_ConsumeEnergy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeEnergyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaEconomyServiceServer).ConsumeEnergy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaEconomyService_ConsumeEnergy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaEconomyServiceServer).ConsumeEnergy(ctx, req.(*ConsumeEnergyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaEconomyService_AddCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaEconomyServiceServer).AddCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaEconomyService_AddCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaEconomyServiceServer).AddCurrency(ctx, req.(*CurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaEconomyService_SpendCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaEconomyServiceServer).SpendCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaEconomyService_SpendCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaEconomyServiceServer).SpendCurrency(ctx, req.(*CurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaEconomyService_GetDailyRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaEconomyServiceServer).GetDailyRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaEconomyService_GetDailyRewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaEconomyServiceServer).GetDailyRewards(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaEconomyService_ClaimDailyReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaEconomyServiceServer).ClaimDailyReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaEconomyService_ClaimDailyReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaEconomyServiceServer).ClaimDailyReward(ctx, req.(*ClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaEconomyService_GetQuests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaEconomyServiceServer).GetQuests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaEconomyService_GetQuests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaEconomyServiceServer).GetQuests(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaEconomyService_ClaimQuestReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaEconomyServiceServer).ClaimQuestReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaEconomyService_ClaimQuestReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaEconomyServiceServer).ClaimQuestReward(ctx, req.(*ClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaEconomyService_GetShopItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaEconomyServiceServer).GetShopItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaEconomyService_GetShopItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaEconomyServiceServer).GetShopItems(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaEconomyService_ShopPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaEconomyServiceServer).ShopPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaEconomyService_ShopPurchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaEconomyServiceServer).ShopPurchase(ctx, req.(*PurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaEconomyService_GetFreePackTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaEconomyServiceServer).GetFreePackTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaEconomyService_GetFreePackTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaEconomyServiceServer).GetFreePackTimer(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GachaEconomyService_ServiceDesc is the grpc.ServiceDesc for GachaEconomyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GachaEconomyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gacha.GachaEconomyService",
	HandlerType: (*GachaEconomyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBanners",
			Handler:    _GachaEconomyService_GetBanners_Handler,
		},
		{
			MethodName: "RollGachaSingle",
			Handler:    _GachaEconomyService_RollGachaSingle_Handler,
		},
		{
			MethodName: "RollGachaMulti",
			Handler:    _GachaEconomyService_RollGachaMulti_Handler,
		},
		{
			MethodName: "GetEnergyState",
			Handler:    _GachaEconomyService_GetEnergyState_Handler,
		},
		{
			MethodName: "ConsumeEnergy",
			Handler:    _GachaEconomyService_ConsumeEnergy_Handler,
		},
		{
			MethodName: "AddCurrency",
			Handler:    _GachaEconomyService_AddCurrency_Handler,
		},
		{
			MethodName: "SpendCurrency",
			Handler:    _GachaEconomyService_SpendCurrency_Handler,
		},
		{
			MethodName: "GetDailyRewards",
			Handler:    _GachaEconomyService_GetDailyRewards_Handler,
		},
		{
			MethodName: "ClaimDailyReward",
			Handler:    _GachaEconomyService_ClaimDailyReward_Handler,
		},
		{
			MethodName: "GetQuests",
			Handler:    _GachaEconomyService_GetQuests_Handler,
		},
		{
			MethodName: "ClaimQuestReward",
			Handler:    _GachaEconomyService_ClaimQuestReward_Handler,
		},
		{
			MethodName: "GetShopItems",
			Handler:    _GachaEconomyService_GetShopItems_Handler,
		},
		{
			MethodName: "ShopPurchase",
			Handler:    _GachaEconomyService_ShopPurchase_Handler,
		},
		{
			MethodName: "GetFreePackTimer",
			Handler:    _GachaEconomyService_GetFreePackTimer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/gacha/gacha.proto",
}
