// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/gacha/gacha.proto

package gacha

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{0}
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{1}
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BannerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banners       []*Banner              `protobuf:"bytes,1,rep,name=banners,proto3" json:"banners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerList) Reset() {
	*x = BannerList{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerList) ProtoMessage() {}

func (x *BannerList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerList.ProtoReflect.Descriptor instead.
func (*BannerList) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{2}
}

func (x *BannerList) GetBanners() []*Banner {
	if x != nil {
		return x.Banners
	}
	return nil
}

type Banner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cost          int32                  `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Banner) Reset() {
	*x = Banner{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{3}
}

func (x *Banner) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Banner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Banner) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type RollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BannerId      string                 `protobuf:"bytes,2,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollRequest) Reset() {
	*x = RollRequest{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollRequest) ProtoMessage() {}

func (x *RollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollRequest.ProtoReflect.Descriptor instead.
func (*RollRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{4}
}

func (x *RollRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RollRequest) GetBannerId() string {
	if x != nil {
		return x.BannerId
	}
	return ""
}

type RollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*PulledCard          `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollResponse) Reset() {
	*x = RollResponse{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollResponse) ProtoMessage() {}

func (x *RollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollResponse.ProtoReflect.Descriptor instead.
func (*RollResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{5}
}

func (x *RollResponse) GetCards() []*PulledCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *RollResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PulledCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsDuplicate   bool                   `protobuf:"varint,4,opt,name=is_duplicate,json=isDuplicate,proto3" json:"is_duplicate,omitempty"`
	NewMergeStars int32                  `protobuf:"varint,5,opt,name=new_merge_stars,json=newMergeStars,proto3" json:"new_merge_stars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PulledCard) Reset() {
	*x = PulledCard{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PulledCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PulledCard) ProtoMessage() {}

func (x *PulledCard) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PulledCard.ProtoReflect.Descriptor instead.
func (*PulledCard) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{6}
}

func (x *PulledCard) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *PulledCard) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *PulledCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PulledCard) GetIsDuplicate() bool {
	if x != nil {
		return x.IsDuplicate
	}
	return false
}

func (x *PulledCard) GetNewMergeStars() int32 {
	if x != nil {
		return x.NewMergeStars
	}
	return 0
}

type EnergyState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CurrentEnergy       int32                  `protobuf:"varint,1,opt,name=current_energy,json=currentEnergy,proto3" json:"current_energy,omitempty"`
	MaxEnergy           int32                  `protobuf:"varint,2,opt,name=max_energy,json=maxEnergy,proto3" json:"max_energy,omitempty"`
	NextRefillTimestamp int64                  `protobuf:"varint,3,opt,name=next_refill_timestamp,json=nextRefillTimestamp,proto3" json:"next_refill_timestamp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnergyState) Reset() {
	*x = EnergyState{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnergyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnergyState) ProtoMessage() {}

func (x *EnergyState) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnergyState.ProtoReflect.Descriptor instead.
func (*EnergyState) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{7}
}

func (x *EnergyState) GetCurrentEnergy() int32 {
	if x != nil {
		return x.CurrentEnergy
	}
	return 0
}

func (x *EnergyState) GetMaxEnergy() int32 {
	if x != nil {
		return x.MaxEnergy
	}
	return 0
}

func (x *EnergyState) GetNextRefillTimestamp() int64 {
	if x != nil {
		return x.NextRefillTimestamp
	}
	return 0
}

type ConsumeEnergyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeEnergyRequest) Reset() {
	*x = ConsumeEnergyRequest{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeEnergyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeEnergyRequest) ProtoMessage() {}

func (x *ConsumeEnergyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeEnergyRequest.ProtoReflect.Descriptor instead.
func (*ConsumeEnergyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{8}
}

func (x *ConsumeEnergyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConsumeEnergyRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ConsumeEnergyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RemainingEnergy int32                  `protobuf:"varint,2,opt,name=remaining_energy,json=remainingEnergy,proto3" json:"remaining_energy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConsumeEnergyResponse) Reset() {
	*x = ConsumeEnergyResponse{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeEnergyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeEnergyResponse) ProtoMessage() {}

func (x *ConsumeEnergyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeEnergyResponse.ProtoReflect.Descriptor instead.
func (*ConsumeEnergyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{9}
}

func (x *ConsumeEnergyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsumeEnergyResponse) GetRemainingEnergy() int32 {
	if x != nil {
		return x.RemainingEnergy
	}
	return 0
}

type CurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyRequest) Reset() {
	*x = CurrencyRequest{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyRequest) ProtoMessage() {}

func (x *CurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyRequest.ProtoReflect.Descriptor instead.
func (*CurrencyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{10}
}

func (x *CurrencyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CurrencyRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewBalance    int32                  `protobuf:"varint,2,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyResponse) Reset() {
	*x = CurrencyResponse{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyResponse) ProtoMessage() {}

func (x *CurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyResponse.ProtoReflect.Descriptor instead.
func (*CurrencyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{11}
}

func (x *CurrencyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CurrencyResponse) GetNewBalance() int32 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

func (x *CurrencyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DailyRewardsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rewards       []*DailyReward         `protobuf:"bytes,1,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyRewardsList) Reset() {
	*x = DailyRewardsList{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyRewardsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyRewardsList) ProtoMessage() {}

func (x *DailyRewardsList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyRewardsList.ProtoReflect.Descriptor instead.
func (*DailyRewardsList) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{12}
}

func (x *DailyRewardsList) GetRewards() []*DailyReward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

type DailyReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Day           int32                  `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Claimed       bool                   `protobuf:"varint,4,opt,name=claimed,proto3" json:"claimed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyReward) Reset() {
	*x = DailyReward{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyReward) ProtoMessage() {}

func (x *DailyReward) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyReward.ProtoReflect.Descriptor instead.
func (*DailyReward) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{13}
}

func (x *DailyReward) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DailyReward) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *DailyReward) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DailyReward) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

type ClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRequest) Reset() {
	*x = ClaimRequest{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRequest) ProtoMessage() {}

func (x *ClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRequest.ProtoReflect.Descriptor instead.
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{14}
}

func (x *ClaimRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClaimRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type ClaimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimResponse) Reset() {
	*x = ClaimResponse{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimResponse) ProtoMessage() {}

func (x *ClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimResponse.ProtoReflect.Descriptor instead.
func (*ClaimResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{15}
}

func (x *ClaimResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClaimResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QuestList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quests        []*Quest               `protobuf:"bytes,1,rep,name=quests,proto3" json:"quests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestList) Reset() {
	*x = QuestList{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestList) ProtoMessage() {}

func (x *QuestList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestList.ProtoReflect.Descriptor instead.
func (*QuestList) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{16}
}

func (x *QuestList) GetQuests() []*Quest {
	if x != nil {
		return x.Quests
	}
	return nil
}

type Quest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	IsCompleted   bool                   `protobuf:"varint,3,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	IsClaimed     bool                   `protobuf:"varint,4,opt,name=is_claimed,json=isClaimed,proto3" json:"is_claimed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quest) Reset() {
	*x = Quest{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quest) ProtoMessage() {}

func (x *Quest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quest.ProtoReflect.Descriptor instead.
func (*Quest) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{17}
}

func (x *Quest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Quest) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *Quest) GetIsClaimed() bool {
	if x != nil {
		return x.IsClaimed
	}
	return false
}

type ShopItemList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ShopItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopItemList) Reset() {
	*x = ShopItemList{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopItemList) ProtoMessage() {}

func (x *ShopItemList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopItemList.ProtoReflect.Descriptor instead.
func (*ShopItemList) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{18}
}

func (x *ShopItemList) GetItems() []*ShopItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ShopItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cost          int32                  `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopItem) Reset() {
	*x = ShopItem{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopItem) ProtoMessage() {}

func (x *ShopItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopItem.ProtoReflect.Descriptor instead.
func (*ShopItem) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{19}
}

func (x *ShopItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShopItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShopItem) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *ShopItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseRequest) Reset() {
	*x = PurchaseRequest{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseRequest) ProtoMessage() {}

func (x *PurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseRequest.ProtoReflect.Descriptor instead.
func (*PurchaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{20}
}

func (x *PurchaseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PurchaseRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type PurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseResponse) Reset() {
	*x = PurchaseResponse{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseResponse) ProtoMessage() {}

func (x *PurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseResponse.ProtoReflect.Descriptor instead.
func (*PurchaseResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{21}
}

func (x *PurchaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PurchaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TimerResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RemainingSeconds int64                  `protobuf:"varint,1,opt,name=remaining_seconds,json=remainingSeconds,proto3" json:"remaining_seconds,omitempty"`
	IsReady          bool                   `protobuf:"varint,2,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TimerResponse) Reset() {
	*x = TimerResponse{}
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerResponse) ProtoMessage() {}

func (x *TimerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gacha_gacha_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerResponse.ProtoReflect.Descriptor instead.
func (*TimerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gacha_gacha_proto_rawDescGZIP(), []int{22}
}

func (x *TimerResponse) GetRemainingSeconds() int64 {
	if x != nil {
		return x.RemainingSeconds
	}
	return 0
}

func (x *TimerResponse) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

var File_api_proto_gacha_gacha_proto protoreflect.FileDescriptor

const file_api_proto_gacha_gacha_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/gacha/gacha.proto\x12\x05gacha\"\a\n" +
	"\x05Empty\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"5\n" +
	"\n" +
	"BannerList\x12'\n" +
	"\abanners\x18\x01 \x03(\v2\r.gacha.BannerR\abanners\"@\n" +
	"\x06Banner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x05R\x04cost\"C\n" +
	"\vRollRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tbanner_id\x18\x02 \x01(\tR\bbannerId\"k\n" +
	"\fRollResponse\x12'\n" +
	"\x05cards\x18\x01 \x03(\v2\x11.gacha.PulledCardR\x05cards\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa5\x01\n" +
	"\n" +
	"PulledCard\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fis_duplicate\x18\x04 \x01(\bR\visDuplicate\x12&\n" +
	"\x0fnew_merge_stars\x18\x05 \x01(\x05R\rnewMergeStars\"\x87\x01\n" +
	"\vEnergyState\x12%\n" +
	"\x0ecurrent_energy\x18\x01 \x01(\x05R\rcurrentEnergy\x12\x1d\n" +
	"\n" +
	"max_energy\x18\x02 \x01(\x05R\tmaxEnergy\x122\n" +
	"\x15next_refill_timestamp\x18\x03 \x01(\x03R\x13nextRefillTimestamp\"G\n" +
	"\x14ConsumeEnergyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"\\\n" +
	"\x15ConsumeEnergyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x10remaining_energy\x18\x02 \x01(\x05R\x0fremainingEnergy\"B\n" +
	"\x0fCurrencyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"g\n" +
	"\x10CurrencyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vnew_balance\x18\x02 \x01(\x05R\n" +
	"newBalance\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"@\n" +
	"\x10DailyRewardsList\x12,\n" +
	"\arewards\x18\x01 \x03(\v2\x12.gacha.DailyRewardR\arewards\"k\n" +
	"\vDailyReward\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03day\x18\x02 \x01(\x05R\x03day\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aclaimed\x18\x04 \x01(\bR\aclaimed\"D\n" +
	"\fClaimRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\"C\n" +
	"\rClaimResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\tQuestList\x12$\n" +
	"\x06quests\x18\x01 \x03(\v2\f.gacha.QuestR\x06quests\"{\n" +
	"\x05Quest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\fis_completed\x18\x03 \x01(\bR\visCompleted\x12\x1d\n" +
	"\n" +
	"is_claimed\x18\x04 \x01(\bR\tisClaimed\"5\n" +
	"\fShopItemList\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.gacha.ShopItemR\x05items\"d\n" +
	"\bShopItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x05R\x04cost\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"C\n" +
	"\x0fPurchaseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\"F\n" +
	"\x10PurchaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\rTimerResponse\x12+\n" +
	"\x11remaining_seconds\x18\x01 \x01(\x03R\x10remainingSeconds\x12\x19\n" +
	"\bis_ready\x18\x02 \x01(\bR\aisReady2\xe6\x06\n" +
	"\x13GachaEconomyService\x12-\n" +
	"\n" +
	"GetBanners\x12\f.gacha.Empty\x1a\x11.gacha.BannerList\x12:\n" +
	"\x0fRollGachaSingle\x12\x12.gacha.RollRequest\x1a\x13.gacha.RollResponse\x129\n" +
	"\x0eRollGachaMulti\x12\x12.gacha.RollRequest\x1a\x13.gacha.RollResponse\x128\n" +
	"\x0eGetEnergyState\x12\x12.gacha.UserRequest\x1a\x12.gacha.EnergyState\x12J\n" +
	"\rConsumeEnergy\x12\x1b.gacha.ConsumeEnergyRequest\x1a\x1c.gacha.ConsumeEnergyResponse\x12>\n" +
	"\vAddCurrency\x12\x16.gacha.CurrencyRequest\x1a\x17.gacha.CurrencyResponse\x12@\n" +
	"\rSpendCurrency\x12\x16.gacha.CurrencyRequest\x1a\x17.gacha.CurrencyResponse\x12>\n" +
	"\x0fGetDailyRewards\x12\x12.gacha.UserRequest\x1a\x17.gacha.DailyRewardsList\x12=\n" +
	"\x10ClaimDailyReward\x12\x13.gacha.ClaimRequest\x1a\x14.gacha.ClaimResponse\x121\n" +
	"\tGetQuests\x12\x12.gacha.UserRequest\x1a\x10.gacha.QuestList\x12=\n" +
	"\x10ClaimQuestReward\x12\x13.gacha.ClaimRequest\x1a\x14.gacha.ClaimResponse\x121\n" +
	"\fGetShopItems\x12\f.gacha.Empty\x1a\x13.gacha.ShopItemList\x12?\n" +
	"\fShopPurchase\x12\x16.gacha.PurchaseRequest\x1a\x17.gacha.PurchaseResponse\x12<\n" +
	"\x10GetFreePackTimer\x12\x12.gacha.UserRequest\x1a\x14.gacha.TimerResponseB.Z,github.com/kozie/lookism-rpg/api/proto/gachab\x06proto3"

var (
	file_api_proto_gacha_gacha_proto_rawDescOnce sync.Once
	file_api_proto_gacha_gacha_proto_rawDescData []byte
)

func file_api_proto_gacha_gacha_proto_rawDescGZIP() []byte {
	file_api_proto_gacha_gacha_proto_rawDescOnce.Do(func() {
		file_api_proto_gacha_gacha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_gacha_gacha_proto_rawDesc), len(file_api_proto_gacha_gacha_proto_rawDesc)))
	})
	return file_api_proto_gacha_gacha_proto_rawDescData
}

var file_api_proto_gacha_gacha_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_gacha_gacha_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: gacha.Empty
	(*UserRequest)(nil),           // 1: gacha.UserRequest
	(*BannerList)(nil),            // 2: gacha.BannerList
	(*Banner)(nil),                // 3: gacha.Banner
	(*RollRequest)(nil),           // 4: gacha.RollRequest
	(*RollResponse)(nil),          // 5: gacha.RollResponse
	(*PulledCard)(nil),            // 6: gacha.PulledCard
	(*EnergyState)(nil),           // 7: gacha.EnergyState
	(*ConsumeEnergyRequest)(nil),  // 8: gacha.ConsumeEnergyRequest
	(*ConsumeEnergyResponse)(nil), // 9: gacha.ConsumeEnergyResponse
	(*CurrencyRequest)(nil),       // 10: gacha.CurrencyRequest
	(*CurrencyResponse)(nil),      // 11: gacha.CurrencyResponse
	(*DailyRewardsList)(nil),      // 12: gacha.DailyRewardsList
	(*DailyReward)(nil),           // 13: gacha.DailyReward
	(*ClaimRequest)(nil),          // 14: gacha.ClaimRequest
	(*ClaimResponse)(nil),         // 15: gacha.ClaimResponse
	(*QuestList)(nil),             // 16: gacha.QuestList
	(*Quest)(nil),                 // 17: gacha.Quest
	(*ShopItemList)(nil),          // 18: gacha.ShopItemList
	(*ShopItem)(nil),              // 19: gacha.ShopItem
	(*PurchaseRequest)(nil),       // 20: gacha.PurchaseRequest
	(*PurchaseResponse)(nil),      // 21: gacha.PurchaseResponse
	(*TimerResponse)(nil),         // 22: gacha.TimerResponse
}
var file_api_proto_gacha_gacha_proto_depIdxs = []int32{
	3,  // 0: gacha.BannerList.banners:type_name -> gacha.Banner
	6,  // 1: gacha.RollResponse.cards:type_name -> gacha.PulledCard
	13, // 2: gacha.DailyRewardsList.rewards:type_name -> gacha.DailyReward
	17, // 3: gacha.QuestList.quests:type_name -> gacha.Quest
	19, // 4: gacha.ShopItemList.items:type_name -> gacha.ShopItem
	0,  // 5: gacha.GachaEconomyService.GetBanners:input_type -> gacha.Empty
	4,  // 6: gacha.GachaEconomyService.RollGachaSingle:input_type -> gacha.RollRequest
	4,  // 7: gacha.GachaEconomyService.RollGachaMulti:input_type -> gacha.RollRequest
	1,  // 8: gacha.GachaEconomyService.GetEnergyState:input_type -> gacha.UserRequest
	8,  // 9: gacha.GachaEconomyService.ConsumeEnergy:input_type -> gacha.ConsumeEnergyRequest
	10, // 10: gacha.GachaEconomyService.AddCurrency:input_type -> gacha.CurrencyRequest
	10, // 11: gacha.GachaEconomyService.SpendCurrency:input_type -> gacha.CurrencyRequest
	1,  // 12: gacha.GachaEconomyService.GetDailyRewards:input_type -> gacha.UserRequest
	14, // 13: gacha.GachaEconomyService.ClaimDailyReward:input_type -> gacha.ClaimRequest
	1,  // 14: gacha.GachaEconomyService.GetQuests:input_type -> gacha.UserRequest
	14, // 15: gacha.GachaEconomyService.ClaimQuestReward:input_type -> gacha.ClaimRequest
	0,  // 16: gacha.GachaEconomyService.GetShopItems:input_type -> gacha.Empty
	20, // 17: gacha.GachaEconomyService.ShopPurchase:input_type -> gacha.PurchaseRequest
	1,  // 18: gacha.GachaEconomyService.GetFreePackTimer:input_type -> gacha.UserRequest
	2,  // 19: gacha.GachaEconomyService.GetBanners:output_type -> gacha.BannerList
	5,  // 20: gacha.GachaEconomyService.RollGachaSingle:output_type -> gacha.RollResponse
	5,  // 21: gacha.GachaEconomyService.RollGachaMulti:output_type -> gacha.RollResponse
	7,  // 22: gacha.GachaEconomyService.GetEnergyState:output_type -> gacha.EnergyState
	9,  // 23: gacha.GachaEconomyService.ConsumeEnergy:output_type -> gacha.ConsumeEnergyResponse
	11, // 24: gacha.GachaEconomyService.AddCurrency:output_type -> gacha.CurrencyResponse
	11, // 25: gacha.GachaEconomyService.SpendCurrency:output_type -> gacha.CurrencyResponse
	12, // 26: gacha.GachaEconomyService.GetDailyRewards:output_type -> gacha.DailyRewardsList
	15, // 27: gacha.GachaEconomyService.ClaimDailyReward:output_type -> gacha.ClaimResponse
	16, // 28: gacha.GachaEconomyService.GetQuests:output_type -> gacha.QuestList
	15, // 29: gacha.GachaEconomyService.ClaimQuestReward:output_type -> gacha.ClaimResponse
	18, // 30: gacha.GachaEconomyService.GetShopItems:output_type -> gacha.ShopItemList
	21, // 31: gacha.GachaEconomyService.ShopPurchase:output_type -> gacha.PurchaseResponse
	22, // 32: gacha.GachaEconomyService.GetFreePackTimer:output_type -> gacha.TimerResponse
	19, // [19:33] is the sub-list for method output_type
	5,  // [5:19] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_gacha_gacha_proto_init() }
func file_api_proto_gacha_gacha_proto_init() {
	if File_api_proto_gacha_gacha_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_gacha_gacha_proto_rawDesc), len(file_api_proto_gacha_gacha_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_gacha_gacha_proto_goTypes,
		DependencyIndexes: file_api_proto_gacha_gacha_proto_depIdxs,
		MessageInfos:      file_api_proto_gacha_gacha_proto_msgTypes,
	}.Build()
	File_api_proto_gacha_gacha_proto = out.File
	file_api_proto_gacha_gacha_proto_goTypes = nil
	file_api_proto_gacha_gacha_proto_depIdxs = nil
}
