// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/notification/notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{0}
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *EmptyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*NotificationRecord  `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *HistoryResponse) GetRecords() []*NotificationRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type NotificationRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	IsRead        bool                   `protobuf:"varint,6,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRecord) Reset() {
	*x = NotificationRecord{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRecord) ProtoMessage() {}

func (x *NotificationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRecord.ProtoReflect.Descriptor instead.
func (*NotificationRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *NotificationRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationRecord) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NotificationRecord) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NotificationRecord) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *NotificationRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type DeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotificationId string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type MarkReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotificationId string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{6}
}

func (x *MarkReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarkReadRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type SettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailEnabled  bool                   `protobuf:"varint,1,opt,name=email_enabled,json=emailEnabled,proto3" json:"email_enabled,omitempty"`
	PushEnabled   bool                   `protobuf:"varint,2,opt,name=push_enabled,json=pushEnabled,proto3" json:"push_enabled,omitempty"`
	SmsEnabled    bool                   `protobuf:"varint,3,opt,name=sms_enabled,json=smsEnabled,proto3" json:"sms_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsResponse) Reset() {
	*x = SettingsResponse{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsResponse) ProtoMessage() {}

func (x *SettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsResponse.ProtoReflect.Descriptor instead.
func (*SettingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{7}
}

func (x *SettingsResponse) GetEmailEnabled() bool {
	if x != nil {
		return x.EmailEnabled
	}
	return false
}

func (x *SettingsResponse) GetPushEnabled() bool {
	if x != nil {
		return x.PushEnabled
	}
	return false
}

func (x *SettingsResponse) GetSmsEnabled() bool {
	if x != nil {
		return x.SmsEnabled
	}
	return false
}

type UpdateSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EmailEnabled  bool                   `protobuf:"varint,2,opt,name=email_enabled,json=emailEnabled,proto3" json:"email_enabled,omitempty"`
	PushEnabled   bool                   `protobuf:"varint,3,opt,name=push_enabled,json=pushEnabled,proto3" json:"push_enabled,omitempty"`
	SmsEnabled    bool                   `protobuf:"varint,4,opt,name=sms_enabled,json=smsEnabled,proto3" json:"sms_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsRequest) Reset() {
	*x = UpdateSettingsRequest{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsRequest) ProtoMessage() {}

func (x *UpdateSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateSettingsRequest) GetEmailEnabled() bool {
	if x != nil {
		return x.EmailEnabled
	}
	return false
}

func (x *UpdateSettingsRequest) GetPushEnabled() bool {
	if x != nil {
		return x.PushEnabled
	}
	return false
}

func (x *UpdateSettingsRequest) GetSmsEnabled() bool {
	if x != nil {
		return x.SmsEnabled
	}
	return false
}

type TemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*TemplateInfo        `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplatesResponse) Reset() {
	*x = TemplatesResponse{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplatesResponse) ProtoMessage() {}

func (x *TemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplatesResponse.ProtoReflect.Descriptor instead.
func (*TemplatesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{9}
}

func (x *TemplatesResponse) GetTemplates() []*TemplateInfo {
	if x != nil {
		return x.Templates
	}
	return nil
}

type TemplateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateInfo) Reset() {
	*x = TemplateInfo{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateInfo) ProtoMessage() {}

func (x *TemplateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateInfo.ProtoReflect.Descriptor instead.
func (*TemplateInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{10}
}

func (x *TemplateInfo) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *TemplateInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewRequest) Reset() {
	*x = PreviewRequest{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRequest) ProtoMessage() {}

func (x *PreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRequest.ProtoReflect.Descriptor instead.
func (*PreviewRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{11}
}

func (x *PreviewRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type PreviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreviewHtml   string                 `protobuf:"bytes,1,opt,name=preview_html,json=previewHtml,proto3" json:"preview_html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewResponse) Reset() {
	*x = PreviewResponse{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewResponse) ProtoMessage() {}

func (x *PreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewResponse.ProtoReflect.Descriptor instead.
func (*PreviewResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{12}
}

func (x *PreviewResponse) GetPreviewHtml() string {
	if x != nil {
		return x.PreviewHtml
	}
	return ""
}

type SendCustomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCustomRequest) Reset() {
	*x = SendCustomRequest{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCustomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCustomRequest) ProtoMessage() {}

func (x *SendCustomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCustomRequest.ProtoReflect.Descriptor instead.
func (*SendCustomRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{13}
}

func (x *SendCustomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendCustomRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendCustomRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type BroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{14}
}

func (x *BroadcastRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *BroadcastRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_api_proto_notification_notification_proto protoreflect.FileDescriptor

const file_api_proto_notification_notification_proto_rawDesc = "" +
	"\n" +
	")api/proto/notification/notification.proto\x12\fnotification\"\x0e\n" +
	"\fEmptyRequest\")\n" +
	"\rEmptyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\x0fHistoryResponse\x12:\n" +
	"\arecords\x18\x01 \x03(\v2 .notification.NotificationRecordR\arecords\"\xb7\x01\n" +
	"\x12NotificationRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x17\n" +
	"\ais_read\x18\x06 \x01(\bR\x06isRead\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"Q\n" +
	"\rDeleteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\"S\n" +
	"\x0fMarkReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\"{\n" +
	"\x10SettingsResponse\x12#\n" +
	"\remail_enabled\x18\x01 \x01(\bR\femailEnabled\x12!\n" +
	"\fpush_enabled\x18\x02 \x01(\bR\vpushEnabled\x12\x1f\n" +
	"\vsms_enabled\x18\x03 \x01(\bR\n" +
	"smsEnabled\"\x99\x01\n" +
	"\x15UpdateSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\remail_enabled\x18\x02 \x01(\bR\femailEnabled\x12!\n" +
	"\fpush_enabled\x18\x03 \x01(\bR\vpushEnabled\x12\x1f\n" +
	"\vsms_enabled\x18\x04 \x01(\bR\n" +
	"smsEnabled\"M\n" +
	"\x11TemplatesResponse\x128\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1a.notification.TemplateInfoR\ttemplates\"Q\n" +
	"\fTemplateInfo\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"1\n" +
	"\x0ePreviewRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\"4\n" +
	"\x0fPreviewResponse\x12!\n" +
	"\fpreview_html\x18\x01 \x01(\tR\vpreviewHtml\"Z\n" +
	"\x11SendCustomRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"@\n" +
	"\x10BroadcastRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body2\xd7\a\n" +
	"\x13NotificationService\x12R\n" +
	"\x16GetNotificationHistory\x12\x19.notification.UserRequest\x1a\x1d.notification.HistoryResponse\x12R\n" +
	"\x18ClearNotificationHistory\x12\x19.notification.UserRequest\x1a\x1b.notification.EmptyResponse\x12N\n" +
	"\x12DeleteNotification\x12\x1b.notification.DeleteRequest\x1a\x1b.notification.EmptyResponse\x12H\n" +
	"\n" +
	"MarkAsRead\x12\x1d.notification.MarkReadRequest\x1a\x1b.notification.EmptyResponse\x12H\n" +
	"\vGetSettings\x12\x19.notification.UserRequest\x1a\x1e.notification.SettingsResponse\x12U\n" +
	"\x0eUpdateSettings\x12#.notification.UpdateSettingsRequest\x1a\x1e.notification.SettingsResponse\x12F\n" +
	"\fOptOutEmails\x12\x19.notification.UserRequest\x1a\x1b.notification.EmptyResponse\x12E\n" +
	"\vOptInEmails\x12\x19.notification.UserRequest\x1a\x1b.notification.EmptyResponse\x12P\n" +
	"\x11GetEmailTemplates\x12\x1a.notification.EmptyRequest\x1a\x1f.notification.TemplatesResponse\x12N\n" +
	"\x0fPreviewTemplate\x12\x1c.notification.PreviewRequest\x1a\x1d.notification.PreviewResponse\x12V\n" +
	"\x16SendCustomNotification\x12\x1f.notification.SendCustomRequest\x1a\x1b.notification.EmptyResponse\x12T\n" +
	"\x15BroadcastNotification\x12\x1e.notification.BroadcastRequest\x1a\x1b.notification.EmptyResponseB5Z3github.com/kozie/lookism-rpg/api/proto/notificationb\x06proto3"

var (
	file_api_proto_notification_notification_proto_rawDescOnce sync.Once
	file_api_proto_notification_notification_proto_rawDescData []byte
)

func file_api_proto_notification_notification_proto_rawDescGZIP() []byte {
	file_api_proto_notification_notification_proto_rawDescOnce.Do(func() {
		file_api_proto_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_notification_notification_proto_rawDesc), len(file_api_proto_notification_notification_proto_rawDesc)))
	})
	return file_api_proto_notification_notification_proto_rawDescData
}

var file_api_proto_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_notification_notification_proto_goTypes = []any{
	(*EmptyRequest)(nil),          // 0: notification.EmptyRequest
	(*EmptyResponse)(nil),         // 1: notification.EmptyResponse
	(*UserRequest)(nil),           // 2: notification.UserRequest
	(*HistoryResponse)(nil),       // 3: notification.HistoryResponse
	(*NotificationRecord)(nil),    // 4: notification.NotificationRecord
	(*DeleteRequest)(nil),         // 5: notification.DeleteRequest
	(*MarkReadRequest)(nil),       // 6: notification.MarkReadRequest
	(*SettingsResponse)(nil),      // 7: notification.SettingsResponse
	(*UpdateSettingsRequest)(nil), // 8: notification.UpdateSettingsRequest
	(*TemplatesResponse)(nil),     // 9: notification.TemplatesResponse
	(*TemplateInfo)(nil),          // 10: notification.TemplateInfo
	(*PreviewRequest)(nil),        // 11: notification.PreviewRequest
	(*PreviewResponse)(nil),       // 12: notification.PreviewResponse
	(*SendCustomRequest)(nil),     // 13: notification.SendCustomRequest
	(*BroadcastRequest)(nil),      // 14: notification.BroadcastRequest
}
var file_api_proto_notification_notification_proto_depIdxs = []int32{
	4,  // 0: notification.HistoryResponse.records:type_name -> notification.NotificationRecord
	10, // 1: notification.TemplatesResponse.templates:type_name -> notification.TemplateInfo
	2,  // 2: notification.NotificationService.GetNotificationHistory:input_type -> notification.UserRequest
	2,  // 3: notification.NotificationService.ClearNotificationHistory:input_type -> notification.UserRequest
	5,  // 4: notification.NotificationService.DeleteNotification:input_type -> notification.DeleteRequest
	6,  // 5: notification.NotificationService.MarkAsRead:input_type -> notification.MarkReadRequest
	2,  // 6: notification.NotificationService.GetSettings:input_type -> notification.UserRequest
	8,  // 7: notification.NotificationService.UpdateSettings:input_type -> notification.UpdateSettingsRequest
	2,  // 8: notification.NotificationService.OptOutEmails:input_type -> notification.UserRequest
	2,  // 9: notification.NotificationService.OptInEmails:input_type -> notification.UserRequest
	0,  // 10: notification.NotificationService.GetEmailTemplates:input_type -> notification.EmptyRequest
	11, // 11: notification.NotificationService.PreviewTemplate:input_type -> notification.PreviewRequest
	13, // 12: notification.NotificationService.SendCustomNotification:input_type -> notification.SendCustomRequest
	14, // 13: notification.NotificationService.BroadcastNotification:input_type -> notification.BroadcastRequest
	3,  // 14: notification.NotificationService.GetNotificationHistory:output_type -> notification.HistoryResponse
	1,  // 15: notification.NotificationService.ClearNotificationHistory:output_type -> notification.EmptyResponse
	1,  // 16: notification.NotificationService.DeleteNotification:output_type -> notification.EmptyResponse
	1,  // 17: notification.NotificationService.MarkAsRead:output_type -> notification.EmptyResponse
	7,  // 18: notification.NotificationService.GetSettings:output_type -> notification.SettingsResponse
	7,  // 19: notification.NotificationService.UpdateSettings:output_type -> notification.SettingsResponse
	1,  // 20: notification.NotificationService.OptOutEmails:output_type -> notification.EmptyResponse
	1,  // 21: notification.NotificationService.OptInEmails:output_type -> notification.EmptyResponse
	9,  // 22: notification.NotificationService.GetEmailTemplates:output_type -> notification.TemplatesResponse
	12, // 23: notification.NotificationService.PreviewTemplate:output_type -> notification.PreviewResponse
	1,  // 24: notification.NotificationService.SendCustomNotification:output_type -> notification.EmptyResponse
	1,  // 25: notification.NotificationService.BroadcastNotification:output_type -> notification.EmptyResponse
	14, // [14:26] is the sub-list for method output_type
	2,  // [2:14] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_notification_notification_proto_init() }
func file_api_proto_notification_notification_proto_init() {
	if File_api_proto_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_notification_notification_proto_rawDesc), len(file_api_proto_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_notification_notification_proto_goTypes,
		DependencyIndexes: file_api_proto_notification_notification_proto_depIdxs,
		MessageInfos:      file_api_proto_notification_notification_proto_msgTypes,
	}.Build()
	File_api_proto_notification_notification_proto = out.File
	file_api_proto_notification_notification_proto_goTypes = nil
	file_api_proto_notification_notification_proto_depIdxs = nil
}
