// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: api/proto/notification/notification.proto

package notification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_GetNotificationHistory_FullMethodName   = "/notification.NotificationService/GetNotificationHistory"
	NotificationService_ClearNotificationHistory_FullMethodName = "/notification.NotificationService/ClearNotificationHistory"
	NotificationService_DeleteNotification_FullMethodName       = "/notification.NotificationService/DeleteNotification"
	NotificationService_MarkAsRead_FullMethodName               = "/notification.NotificationService/MarkAsRead"
	NotificationService_GetSettings_FullMethodName              = "/notification.NotificationService/GetSettings"
	NotificationService_UpdateSettings_FullMethodName           = "/notification.NotificationService/UpdateSettings"
	NotificationService_OptOutEmails_FullMethodName             = "/notification.NotificationService/OptOutEmails"
	NotificationService_OptInEmails_FullMethodName              = "/notification.NotificationService/OptInEmails"
	NotificationService_GetEmailTemplates_FullMethodName        = "/notification.NotificationService/GetEmailTemplates"
	NotificationService_PreviewTemplate_FullMethodName          = "/notification.NotificationService/PreviewTemplate"
	NotificationService_SendCustomNotification_FullMethodName   = "/notification.NotificationService/SendCustomNotification"
	NotificationService_BroadcastNotification_FullMethodName    = "/notification.NotificationService/BroadcastNotification"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	// History
	GetNotificationHistory(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
	ClearNotificationHistory(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	DeleteNotification(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	MarkAsRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Settings
	GetSettings(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*SettingsResponse, error)
	UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*SettingsResponse, error)
	OptOutEmails(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	OptInEmails(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Templates
	GetEmailTemplates(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*TemplatesResponse, error)
	PreviewTemplate(ctx context.Context, in *PreviewRequest, opts ...grpc.CallOption) (*PreviewResponse, error)
	// Manual dispatch (admin)
	SendCustomNotification(ctx context.Context, in *SendCustomRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	BroadcastNotification(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) GetNotificationHistory(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetNotificationHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) ClearNotificationHistory(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, NotificationService_ClearNotificationHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) DeleteNotification(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, NotificationService_DeleteNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) MarkAsRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, NotificationService_MarkAsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetSettings(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*SettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingsResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*SettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingsResponse)
	err := c.cc.Invoke(ctx, NotificationService_UpdateSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) OptOutEmails(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, NotificationService_OptOutEmails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) OptInEmails(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, NotificationService_OptInEmails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetEmailTemplates(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*TemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplatesResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetEmailTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) PreviewTemplate(ctx context.Context, in *PreviewRequest, opts ...grpc.CallOption) (*PreviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewResponse)
	err := c.cc.Invoke(ctx, NotificationService_PreviewTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendCustomNotification(ctx context.Context, in *SendCustomRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, NotificationService_SendCustomNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) BroadcastNotification(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, NotificationService_BroadcastNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	// History
	GetNotificationHistory(context.Context, *UserRequest) (*HistoryResponse, error)
	ClearNotificationHistory(context.Context, *UserRequest) (*EmptyResponse, error)
	DeleteNotification(context.Context, *DeleteRequest) (*EmptyResponse, error)
	MarkAsRead(context.Context, *MarkReadRequest) (*EmptyResponse, error)
	// Settings
	GetSettings(context.Context, *UserRequest) (*SettingsResponse, error)
	UpdateSettings(context.Context, *UpdateSettingsRequest) (*SettingsResponse, error)
	OptOutEmails(context.Context, *UserRequest) (*EmptyResponse, error)
	OptInEmails(context.Context, *UserRequest) (*EmptyResponse, error)
	// Templates
	GetEmailTemplates(context.Context, *EmptyRequest) (*TemplatesResponse, error)
	PreviewTemplate(context.Context, *PreviewRequest) (*PreviewResponse, error)
	// Manual dispatch (admin)
	SendCustomNotification(context.Context, *SendCustomRequest) (*EmptyResponse, error)
	BroadcastNotification(context.Context, *BroadcastRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) GetNotificationHistory(context.Context, *UserRequest) (*HistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotificationHistory not implemented")
}
func (UnimplementedNotificationServiceServer) ClearNotificationHistory(context.Context, *UserRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearNotificationHistory not implemented")
}
func (UnimplementedNotificationServiceServer) DeleteNotification(context.Context, *DeleteRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNotification not implemented")
}
func (UnimplementedNotificationServiceServer) MarkAsRead(context.Context, *MarkReadRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAsRead not implemented")
}
func (UnimplementedNotificationServiceServer) GetSettings(context.Context, *UserRequest) (*SettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedNotificationServiceServer) UpdateSettings(context.Context, *UpdateSettingsRequest) (*SettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSettings not implemented")
}
func (UnimplementedNotificationServiceServer) OptOutEmails(context.Context, *UserRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OptOutEmails not implemented")
}
func (UnimplementedNotificationServiceServer) OptInEmails(context.Context, *UserRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OptInEmails not implemented")
}
func (UnimplementedNotificationServiceServer) GetEmailTemplates(context.Context, *EmptyRequest) (*TemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmailTemplates not implemented")
}
func (UnimplementedNotificationServiceServer) PreviewTemplate(context.Context, *PreviewRequest) (*PreviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewTemplate not implemented")
}
func (UnimplementedNotificationServiceServer) SendCustomNotification(context.Context, *SendCustomRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCustomNotification not implemented")
}
func (UnimplementedNotificationServiceServer) BroadcastNotification(context.Context, *BroadcastRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BroadcastNotification not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_GetNotificationHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetNotificationHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetNotificationHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetNotificationHistory(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_ClearNotificationHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ClearNotificationHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ClearNotificationHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ClearNotificationHistory(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_DeleteNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).DeleteNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_DeleteNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).DeleteNotification(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_MarkAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).MarkAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_MarkAsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).MarkAsRead(ctx, req.(*MarkReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetSettings(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_UpdateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).UpdateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_UpdateSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).UpdateSettings(ctx, req.(*UpdateSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_OptOutEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).OptOutEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_OptOutEmails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).OptOutEmails(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_OptInEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).OptInEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_OptInEmails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).OptInEmails(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetEmailTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetEmailTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetEmailTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetEmailTemplates(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_PreviewTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).PreviewTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_PreviewTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).PreviewTemplate(ctx, req.(*PreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendCustomNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCustomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendCustomNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendCustomNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendCustomNotification(ctx, req.(*SendCustomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_BroadcastNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).BroadcastNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_BroadcastNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).BroadcastNotification(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNotificationHistory",
			Handler:    _NotificationService_GetNotificationHistory_Handler,
		},
		{
			MethodName: "ClearNotificationHistory",
			Handler:    _NotificationService_ClearNotificationHistory_Handler,
		},
		{
			MethodName: "DeleteNotification",
			Handler:    _NotificationService_DeleteNotification_Handler,
		},
		{
			MethodName: "MarkAsRead",
			Handler:    _NotificationService_MarkAsRead_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _NotificationService_GetSettings_Handler,
		},
		{
			MethodName: "UpdateSettings",
			Handler:    _NotificationService_UpdateSettings_Handler,
		},
		{
			MethodName: "OptOutEmails",
			Handler:    _NotificationService_OptOutEmails_Handler,
		},
		{
			MethodName: "OptInEmails",
			Handler:    _NotificationService_OptInEmails_Handler,
		},
		{
			MethodName: "GetEmailTemplates",
			Handler:    _NotificationService_GetEmailTemplates_Handler,
		},
		{
			MethodName: "PreviewTemplate",
			Handler:    _NotificationService_PreviewTemplate_Handler,
		},
		{
			MethodName: "SendCustomNotification",
			Handler:    _NotificationService_SendCustomNotification_Handler,
		},
		{
			MethodName: "BroadcastNotification",
			Handler:    _NotificationService_BroadcastNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/notification/notification.proto",
}
