// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{0}
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_api_proto_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ConsumeCardEnergyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardIds       []string               `protobuf:"bytes,2,rep,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeCardEnergyRequest) Reset() {
	*x = ConsumeCardEnergyRequest{}
	mi := &file_api_proto_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeCardEnergyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeCardEnergyRequest) ProtoMessage() {}

func (x *ConsumeCardEnergyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeCardEnergyRequest.ProtoReflect.Descriptor instead.
func (*ConsumeCardEnergyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumeCardEnergyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConsumeCardEnergyRequest) GetCardIds() []string {
	if x != nil {
		return x.CardIds
	}
	return nil
}

type ConsumeCardEnergyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeCardEnergyResponse) Reset() {
	*x = ConsumeCardEnergyResponse{}
	mi := &file_api_proto_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeCardEnergyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeCardEnergyResponse) ProtoMessage() {}

func (x *ConsumeCardEnergyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeCardEnergyResponse.ProtoReflect.Descriptor instead.
func (*ConsumeCardEnergyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *ConsumeCardEnergyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsumeCardEnergyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_proto_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_api_proto_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_api_proto_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *TokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_api_proto_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *TokenResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *TokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewUsername   string                 `protobuf:"bytes,2,opt,name=new_username,json=newUsername,proto3" json:"new_username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_api_proto_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetNewUsername() string {
	if x != nil {
		return x.NewUsername
	}
	return ""
}

type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_api_proto_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *ProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProfileResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessResponse) Reset() {
	*x = SuccessResponse{}
	mi := &file_api_proto_user_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResponse) ProtoMessage() {}

func (x *SuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResponse.ProtoReflect.Descriptor instead.
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{11}
}

func (x *SuccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SuccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryResponse) Reset() {
	*x = InventoryResponse{}
	mi := &file_api_proto_user_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryResponse) ProtoMessage() {}

func (x *InventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryResponse.ProtoReflect.Descriptor instead.
func (*InventoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{12}
}

func (x *InventoryResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type AddCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCardRequest) Reset() {
	*x = AddCardRequest{}
	mi := &file_api_proto_user_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCardRequest) ProtoMessage() {}

func (x *AddCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCardRequest.ProtoReflect.Descriptor instead.
func (*AddCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{13}
}

func (x *AddCardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddCardRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type LevelUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardId        string                 `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelUpRequest) Reset() {
	*x = LevelUpRequest{}
	mi := &file_api_proto_user_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelUpRequest) ProtoMessage() {}

func (x *LevelUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelUpRequest.ProtoReflect.Descriptor instead.
func (*LevelUpRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{14}
}

func (x *LevelUpRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LevelUpRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type MergeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardId        string                 `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeRequest) Reset() {
	*x = MergeRequest{}
	mi := &file_api_proto_user_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRequest) ProtoMessage() {}

func (x *MergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRequest.ProtoReflect.Descriptor instead.
func (*MergeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{15}
}

func (x *MergeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MergeRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type CardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardRequest) Reset() {
	*x = CardRequest{}
	mi := &file_api_proto_user_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardRequest) ProtoMessage() {}

func (x *CardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardRequest.ProtoReflect.Descriptor instead.
func (*CardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{16}
}

func (x *CardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type Card struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId           string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Level                int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	MergeStars           int32                  `protobuf:"varint,4,opt,name=merge_stars,json=mergeStars,proto3" json:"merge_stars,omitempty"`
	CurrentEnergy        int32                  `protobuf:"varint,5,opt,name=current_energy,json=currentEnergy,proto3" json:"current_energy,omitempty"`
	NextRefreshTimestamp int64                  `protobuf:"varint,6,opt,name=next_refresh_timestamp,json=nextRefreshTimestamp,proto3" json:"next_refresh_timestamp,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_api_proto_user_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{17}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *Card) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Card) GetMergeStars() int32 {
	if x != nil {
		return x.MergeStars
	}
	return 0
}

func (x *Card) GetCurrentEnergy() int32 {
	if x != nil {
		return x.CurrentEnergy
	}
	return 0
}

func (x *Card) GetNextRefreshTimestamp() int64 {
	if x != nil {
		return x.NextRefreshTimestamp
	}
	return 0
}

type CardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResponse) Reset() {
	*x = CardResponse{}
	mi := &file_api_proto_user_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponse) ProtoMessage() {}

func (x *CardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponse.ProtoReflect.Descriptor instead.
func (*CardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{18}
}

func (x *CardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *CardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CardStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CardId          string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FinalHp         int32                  `protobuf:"varint,3,opt,name=final_hp,json=finalHp,proto3" json:"final_hp,omitempty"`
	FinalStr        int32                  `protobuf:"varint,4,opt,name=final_str,json=finalStr,proto3" json:"final_str,omitempty"`
	FinalMana       int32                  `protobuf:"varint,5,opt,name=final_mana,json=finalMana,proto3" json:"final_mana,omitempty"`
	FinalAgility    int32                  `protobuf:"varint,6,opt,name=final_agility,json=finalAgility,proto3" json:"final_agility,omitempty"`
	FinalReaction   int32                  `protobuf:"varint,7,opt,name=final_reaction,json=finalReaction,proto3" json:"final_reaction,omitempty"`
	FinalDurability int32                  `protobuf:"varint,8,opt,name=final_durability,json=finalDurability,proto3" json:"final_durability,omitempty"`
	FinalPower      float32                `protobuf:"fixed32,9,opt,name=final_power,json=finalPower,proto3" json:"final_power,omitempty"`
	FinalSpeed      float32                `protobuf:"fixed32,10,opt,name=final_speed,json=finalSpeed,proto3" json:"final_speed,omitempty"`
	FinalTechnique  float32                `protobuf:"fixed32,11,opt,name=final_technique,json=finalTechnique,proto3" json:"final_technique,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CardStatsResponse) Reset() {
	*x = CardStatsResponse{}
	mi := &file_api_proto_user_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardStatsResponse) ProtoMessage() {}

func (x *CardStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardStatsResponse.ProtoReflect.Descriptor instead.
func (*CardStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{19}
}

func (x *CardStatsResponse) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardStatsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CardStatsResponse) GetFinalHp() int32 {
	if x != nil {
		return x.FinalHp
	}
	return 0
}

func (x *CardStatsResponse) GetFinalStr() int32 {
	if x != nil {
		return x.FinalStr
	}
	return 0
}

func (x *CardStatsResponse) GetFinalMana() int32 {
	if x != nil {
		return x.FinalMana
	}
	return 0
}

func (x *CardStatsResponse) GetFinalAgility() int32 {
	if x != nil {
		return x.FinalAgility
	}
	return 0
}

func (x *CardStatsResponse) GetFinalReaction() int32 {
	if x != nil {
		return x.FinalReaction
	}
	return 0
}

func (x *CardStatsResponse) GetFinalDurability() int32 {
	if x != nil {
		return x.FinalDurability
	}
	return 0
}

func (x *CardStatsResponse) GetFinalPower() float32 {
	if x != nil {
		return x.FinalPower
	}
	return 0
}

func (x *CardStatsResponse) GetFinalSpeed() float32 {
	if x != nil {
		return x.FinalSpeed
	}
	return 0
}

func (x *CardStatsResponse) GetFinalTechnique() float32 {
	if x != nil {
		return x.FinalTechnique
	}
	return 0
}

type SquadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardIds       []string               `protobuf:"bytes,2,rep,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SquadRequest) Reset() {
	*x = SquadRequest{}
	mi := &file_api_proto_user_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SquadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SquadRequest) ProtoMessage() {}

func (x *SquadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SquadRequest.ProtoReflect.Descriptor instead.
func (*SquadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{20}
}

func (x *SquadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SquadRequest) GetCardIds() []string {
	if x != nil {
		return x.CardIds
	}
	return nil
}

type SquadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Squad         []*Card                `protobuf:"bytes,2,rep,name=squad,proto3" json:"squad,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SquadResponse) Reset() {
	*x = SquadResponse{}
	mi := &file_api_proto_user_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SquadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SquadResponse) ProtoMessage() {}

func (x *SquadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SquadResponse.ProtoReflect.Descriptor instead.
func (*SquadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{21}
}

func (x *SquadResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SquadResponse) GetSquad() []*Card {
	if x != nil {
		return x.Squad
	}
	return nil
}

func (x *SquadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_user_user_proto protoreflect.FileDescriptor

const file_api_proto_user_user_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/user/user.proto\x12\x04user\"\a\n" +
	"\x05Empty\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"N\n" +
	"\x18ConsumeCardEnergyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bcard_ids\x18\x02 \x03(\tR\acardIds\"O\n" +
	"\x19ConsumeCardEnergyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"_\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"s\n" +
	"\fAuthResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"$\n" +
	"\fTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"C\n" +
	"\rTokenResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"R\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fnew_username\x18\x02 \x01(\tR\vnewUsername\"\x95\x01\n" +
	"\x0fProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\"E\n" +
	"\x0fSuccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x11InventoryResponse\x12 \n" +
	"\x05cards\x18\x01 \x03(\v2\n" +
	".user.CardR\x05cards\"J\n" +
	"\x0eAddCardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\"B\n" +
	"\x0eLevelUpRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\"@\n" +
	"\fMergeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\"&\n" +
	"\vCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"\xcb\x01\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x1f\n" +
	"\vmerge_stars\x18\x04 \x01(\x05R\n" +
	"mergeStars\x12%\n" +
	"\x0ecurrent_energy\x18\x05 \x01(\x05R\rcurrentEnergy\x124\n" +
	"\x16next_refresh_timestamp\x18\x06 \x01(\x03R\x14nextRefreshTimestamp\"b\n" +
	"\fCardResponse\x12\x1e\n" +
	"\x04card\x18\x01 \x01(\v2\n" +
	".user.CardR\x04card\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xf9\x02\n" +
	"\x11CardStatsResponse\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bfinal_hp\x18\x03 \x01(\x05R\afinalHp\x12\x1b\n" +
	"\tfinal_str\x18\x04 \x01(\x05R\bfinalStr\x12\x1d\n" +
	"\n" +
	"final_mana\x18\x05 \x01(\x05R\tfinalMana\x12#\n" +
	"\rfinal_agility\x18\x06 \x01(\x05R\ffinalAgility\x12%\n" +
	"\x0efinal_reaction\x18\a \x01(\x05R\rfinalReaction\x12)\n" +
	"\x10final_durability\x18\b \x01(\x05R\x0ffinalDurability\x12\x1f\n" +
	"\vfinal_power\x18\t \x01(\x02R\n" +
	"finalPower\x12\x1f\n" +
	"\vfinal_speed\x18\n" +
	" \x01(\x02R\n" +
	"finalSpeed\x12'\n" +
	"\x0ffinal_technique\x18\v \x01(\x02R\x0efinalTechnique\"B\n" +
	"\fSquadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bcard_ids\x18\x02 \x03(\tR\acardIds\"d\n" +
	"\rSquadResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\x05squad\x18\x02 \x03(\v2\n" +
	".user.CardR\x05squad\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2\xa5\x06\n" +
	"\vUserService\x125\n" +
	"\bRegister\x12\x15.user.RegisterRequest\x1a\x12.user.AuthResponse\x12/\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x12.user.AuthResponse\x128\n" +
	"\rValidateToken\x12\x12.user.TokenRequest\x1a\x13.user.TokenResponse\x126\n" +
	"\n" +
	"GetProfile\x12\x11.user.UserRequest\x1a\x15.user.ProfileResponse\x12B\n" +
	"\rUpdateProfile\x12\x1a.user.UpdateProfileRequest\x1a\x15.user.ProfileResponse\x12:\n" +
	"\fGetInventory\x12\x11.user.UserRequest\x1a\x17.user.InventoryResponse\x12>\n" +
	"\x12AddCardToInventory\x12\x14.user.AddCardRequest\x1a\x12.user.CardResponse\x127\n" +
	"\vLevelUpCard\x12\x14.user.LevelUpRequest\x1a\x12.user.CardResponse\x12<\n" +
	"\x12MergeDuplicateCard\x12\x12.user.MergeRequest\x1a\x12.user.CardResponse\x12:\n" +
	"\fGetCardStats\x12\x11.user.CardRequest\x1a\x17.user.CardStatsResponse\x129\n" +
	"\x0eSetActiveSquad\x12\x12.user.SquadRequest\x1a\x13.user.SquadResponse\x128\n" +
	"\x0eGetActiveSquad\x12\x11.user.UserRequest\x1a\x13.user.SquadResponse\x12T\n" +
	"\x11ConsumeCardEnergy\x12\x1e.user.ConsumeCardEnergyRequest\x1a\x1f.user.ConsumeCardEnergyResponseB-Z+github.com/kozie/lookism-rpg/api/proto/userb\x06proto3"

var (
	file_api_proto_user_user_proto_rawDescOnce sync.Once
	file_api_proto_user_user_proto_rawDescData []byte
)

func file_api_proto_user_user_proto_rawDescGZIP() []byte {
	file_api_proto_user_user_proto_rawDescOnce.Do(func() {
		file_api_proto_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_user_user_proto_rawDesc), len(file_api_proto_user_user_proto_rawDesc)))
	})
	return file_api_proto_user_user_proto_rawDescData
}

var file_api_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_proto_user_user_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: user.Empty
	(*UserRequest)(nil),               // 1: user.UserRequest
	(*ConsumeCardEnergyRequest)(nil),  // 2: user.ConsumeCardEnergyRequest
	(*ConsumeCardEnergyResponse)(nil), // 3: user.ConsumeCardEnergyResponse
	(*RegisterRequest)(nil),           // 4: user.RegisterRequest
	(*LoginRequest)(nil),              // 5: user.LoginRequest
	(*AuthResponse)(nil),              // 6: user.AuthResponse
	(*TokenRequest)(nil),              // 7: user.TokenRequest
	(*TokenResponse)(nil),             // 8: user.TokenResponse
	(*UpdateProfileRequest)(nil),      // 9: user.UpdateProfileRequest
	(*ProfileResponse)(nil),           // 10: user.ProfileResponse
	(*SuccessResponse)(nil),           // 11: user.SuccessResponse
	(*InventoryResponse)(nil),         // 12: user.InventoryResponse
	(*AddCardRequest)(nil),            // 13: user.AddCardRequest
	(*LevelUpRequest)(nil),            // 14: user.LevelUpRequest
	(*MergeRequest)(nil),              // 15: user.MergeRequest
	(*CardRequest)(nil),               // 16: user.CardRequest
	(*Card)(nil),                      // 17: user.Card
	(*CardResponse)(nil),              // 18: user.CardResponse
	(*CardStatsResponse)(nil),         // 19: user.CardStatsResponse
	(*SquadRequest)(nil),              // 20: user.SquadRequest
	(*SquadResponse)(nil),             // 21: user.SquadResponse
}
var file_api_proto_user_user_proto_depIdxs = []int32{
	17, // 0: user.InventoryResponse.cards:type_name -> user.Card
	17, // 1: user.CardResponse.card:type_name -> user.Card
	17, // 2: user.SquadResponse.squad:type_name -> user.Card
	4,  // 3: user.UserService.Register:input_type -> user.RegisterRequest
	5,  // 4: user.UserService.Login:input_type -> user.LoginRequest
	7,  // 5: user.UserService.ValidateToken:input_type -> user.TokenRequest
	1,  // 6: user.UserService.GetProfile:input_type -> user.UserRequest
	9,  // 7: user.UserService.UpdateProfile:input_type -> user.UpdateProfileRequest
	1,  // 8: user.UserService.GetInventory:input_type -> user.UserRequest
	13, // 9: user.UserService.AddCardToInventory:input_type -> user.AddCardRequest
	14, // 10: user.UserService.LevelUpCard:input_type -> user.LevelUpRequest
	15, // 11: user.UserService.MergeDuplicateCard:input_type -> user.MergeRequest
	16, // 12: user.UserService.GetCardStats:input_type -> user.CardRequest
	20, // 13: user.UserService.SetActiveSquad:input_type -> user.SquadRequest
	1,  // 14: user.UserService.GetActiveSquad:input_type -> user.UserRequest
	2,  // 15: user.UserService.ConsumeCardEnergy:input_type -> user.ConsumeCardEnergyRequest
	6,  // 16: user.UserService.Register:output_type -> user.AuthResponse
	6,  // 17: user.UserService.Login:output_type -> user.AuthResponse
	8,  // 18: user.UserService.ValidateToken:output_type -> user.TokenResponse
	10, // 19: user.UserService.GetProfile:output_type -> user.ProfileResponse
	10, // 20: user.UserService.UpdateProfile:output_type -> user.ProfileResponse
	12, // 21: user.UserService.GetInventory:output_type -> user.InventoryResponse
	18, // 22: user.UserService.AddCardToInventory:output_type -> user.CardResponse
	18, // 23: user.UserService.LevelUpCard:output_type -> user.CardResponse
	18, // 24: user.UserService.MergeDuplicateCard:output_type -> user.CardResponse
	19, // 25: user.UserService.GetCardStats:output_type -> user.CardStatsResponse
	21, // 26: user.UserService.SetActiveSquad:output_type -> user.SquadResponse
	21, // 27: user.UserService.GetActiveSquad:output_type -> user.SquadResponse
	3,  // 28: user.UserService.ConsumeCardEnergy:output_type -> user.ConsumeCardEnergyResponse
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_user_user_proto_init() }
func file_api_proto_user_user_proto_init() {
	if File_api_proto_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_user_user_proto_rawDesc), len(file_api_proto_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_user_user_proto_goTypes,
		DependencyIndexes: file_api_proto_user_user_proto_depIdxs,
		MessageInfos:      file_api_proto_user_user_proto_msgTypes,
	}.Build()
	File_api_proto_user_user_proto = out.File
	file_api_proto_user_user_proto_goTypes = nil
	file_api_proto_user_user_proto_depIdxs = nil
}
